export type Proverb = {
  id: number;
  language: 'fa' | 'de';
  proverb: string;
  equivalent: string;
  meaning: string;
  category: string;
  note: string;
};

export const additionalProverbs: Proverb[] = [
  {
    id: 17,
    language: 'fa',
    proverb: 'آب که از سر گذشت، چه یک وجب چه صد وجب',
    equivalent: 'Wenn schon, denn schon.',
    meaning:
      'Ist eine entscheidende Grenze erst überschritten, macht das Ausmaß des Problems oft keinen großen Unterschied mehr.',
    category: 'Alltag',
    note: 'Wörtlich: Wenn das Wasser über den Kopf reicht, ist eine Handbreit so viel wie hundert.',
  },
  {
    id: 18,
    language: 'fa',
    proverb: 'آب در کوزه و ما تشنه‌لبان می‌گردیم',
    equivalent: 'Warum in die Ferne schweifen? Sieh, das Gute liegt so nah.',
    meaning:
      'Oft suchen wir weit weg nach etwas, das sich längst ganz in unserer Nähe befindet.',
    category: 'Weisheit',
    note: 'Wörtlich: Das Wasser ist im Krug, und wir irren durstig umher.',
  },
  {
    id: 19,
    language: 'fa',
    proverb: 'آب رفته به جوی بازنمی‌گردد',
    equivalent: 'Geschehen ist geschehen.',
    meaning:
      'Vergangenes lässt sich nicht rückgängig machen; man muss nach vorn schauen.',
    category: 'Weisheit',
    note: 'Wörtlich: Abgeflossenes Wasser kehrt nicht in den Bach zurück.',
  },
  {
    id: 20,
    language: 'fa',
    proverb: 'آب از آب تکان نمی‌خورد',
    equivalent: 'Es rührt sich nichts.',
    meaning:
      'Trotz einer erwarteten Veränderung bleibt alles vollkommen ruhig und unverändert.',
    category: 'Alltag',
    note: 'Wörtlich: Nicht einmal Wasser bewegt sich vom Wasser.',
  },
  {
    id: 21,
    language: 'fa',
    proverb: 'آب را گل‌آلود می‌کند تا ماهی بگیرد',
    equivalent: 'Im Trüben fischen.',
    meaning:
      'Jemand schafft absichtlich Unklarheit, um aus der Verwirrung einen Vorteil zu ziehen.',
    category: 'Alltag',
    note: 'Wörtlich: Er trübt das Wasser, um einen Fisch zu fangen.',
  },
  {
    id: 22,
    language: 'fa',
    proverb: 'آفتابه لگن هفت دست، شام و ناهار هیچی',
    equivalent: 'Außen hui, innen pfui.',
    meaning:
      'Großer Aufwand und schöner Schein verbergen, dass es am Wesentlichen fehlt.',
    category: 'Alltag',
    note: 'Wörtlich: Sieben Garnituren Kanne und Schüssel, aber weder Mittag- noch Abendessen.',
  },
  {
    id: 23,
    language: 'fa',
    proverb: 'از این ستون به آن ستون فرج است',
    equivalent: 'Kommt Zeit, kommt Rat.',
    meaning:
      'Ein wenig Aufschub kann neue Möglichkeiten bringen und eine schwierige Lage verbessern.',
    category: 'Geduld',
    note: 'Wörtlich: Von dieser Säule bis zur nächsten kann Erlösung kommen.',
  },
  {
    id: 24,
    language: 'fa',
    proverb: 'از کوزه همان برون تراود که در اوست',
    equivalent: 'Wes das Herz voll ist, des geht der Mund über.',
    meaning:
      'Das Verhalten und die Worte eines Menschen zeigen, was wirklich in ihm steckt.',
    category: 'Weisheit',
    note: 'Wörtlich: Aus dem Krug tritt nur das heraus, was in ihm ist.',
  },
  {
    id: 25,
    language: 'fa',
    proverb: 'از ماست که بر ماست',
    equivalent: 'Wie man sich bettet, so liegt man.',
    meaning:
      'Viele Schwierigkeiten entstehen durch das eigene Verhalten oder die eigenen Entscheidungen.',
    category: 'Weisheit',
    note: 'Wörtlich: Was uns trifft, kommt von uns selbst.',
  },
  {
    id: 26,
    language: 'fa',
    proverb: 'با یک دست دو هندوانه نمی‌شود برداشت',
    equivalent: 'Man kann nicht auf zwei Hochzeiten gleichzeitig tanzen.',
    meaning:
      'Wer zu viele anspruchsvolle Aufgaben gleichzeitig übernimmt, bewältigt oft keine davon gut.',
    category: 'Arbeit',
    note: 'Wörtlich: Mit einer Hand kann man nicht zwei Wassermelonen tragen.',
  },
  {
    id: 27,
    language: 'fa',
    proverb: 'بار کج به منزل نمی‌رسد',
    equivalent: 'Ehrlich währt am längsten.',
    meaning:
      'Ein Vorhaben, das auf Unehrlichkeit beruht, führt langfristig nicht zum Ziel.',
    category: 'Weisheit',
    note: 'Wörtlich: Eine schiefe Last erreicht ihr Ziel nicht.',
  },
  {
    id: 28,
    language: 'fa',
    proverb: 'بادآورده را باد می‌برد',
    equivalent: 'Wie gewonnen, so zerronnen.',
    meaning:
      'Was ohne Mühe oder festen Grund gewonnen wurde, ist häufig ebenso schnell wieder verloren.',
    category: 'Alltag',
    note: 'Wörtlich: Was der Wind bringt, nimmt der Wind wieder mit.',
  },
  {
    id: 29,
    language: 'fa',
    proverb: 'بنی‌آدم اعضای یکدیگرند',
    equivalent: 'Einer für alle, alle für einen.',
    meaning:
      'Menschen sind miteinander verbunden und sollten das Leid anderer nicht gleichgültig hinnehmen.',
    category: 'Zusammenarbeit',
    note: 'Wörtlich: Die Menschenkinder sind Glieder eines Körpers.',
  },
  {
    id: 30,
    language: 'fa',
    proverb: 'تا نباشد چیزکی، مردم نگویند چیزها',
    equivalent: 'Wo Rauch ist, ist auch Feuer.',
    meaning:
      'Ein hartnäckiges Gerücht besitzt manchmal zumindest einen kleinen wahren Kern.',
    category: 'Alltag',
    note: 'Wörtlich: Gäbe es nicht eine Kleinigkeit, würden die Leute nicht so vieles erzählen.',
  },
  {
    id: 31,
    language: 'fa',
    proverb: 'جلوی ضرر را از هر جا بگیری منفعت است',
    equivalent: 'Besser spät als nie.',
    meaning:
      'Auch eine verspätete Korrektur ist wertvoll, wenn sie weiteren Schaden verhindert.',
    category: 'Gelegenheit',
    note: 'Wörtlich: Wo immer man einen Verlust stoppt, beginnt der Gewinn.',
  },
  {
    id: 32,
    language: 'fa',
    proverb: 'جواب ابلهان خاموشی است',
    equivalent: 'Die beste Antwort ist Schweigen.',
    meaning:
      'Auf törichte oder provozierende Worte reagiert man manchmal am klügsten gar nicht.',
    category: 'Weisheit',
    note: 'Wörtlich: Die Antwort der Narren ist Schweigen.',
  },
  {
    id: 33,
    language: 'fa',
    proverb: 'چراغی که به خانه رواست، به مسجد حرام است',
    equivalent: 'Das Hemd ist mir näher als der Rock.',
    meaning:
      'Bevor man anderswo hilft, sollte man berechtigte Bedürfnisse der eigenen Familie berücksichtigen.',
    category: 'Alltag',
    note: 'Wörtlich: Eine Lampe, die das Haus braucht, gehört nicht in die Moschee.',
  },
  {
    id: 34,
    language: 'fa',
    proverb: 'چاه مکن بهر کسی، اول خودت دوم کسی',
    equivalent: 'Wer anderen eine Grube gräbt, fällt selbst hinein.',
    meaning:
      'Wer anderen schaden will, wird häufig selbst zum Opfer des eigenen Plans.',
    category: 'Weisheit',
    note: 'Wörtlich: Grabe niemandem eine Grube; zuerst fällst du hinein, dann der andere.',
  },
  {
    id: 35,
    language: 'fa',
    proverb: 'خشت اول چون نهد معمار کج، تا ثریا می‌رود دیوار کج',
    equivalent: 'Wehret den Anfängen.',
    meaning:
      'Ein Fehler am Anfang setzt sich fort und wird später immer schwerer zu korrigieren.',
    category: 'Arbeit',
    note: 'Wörtlich: Setzt der Maurer den ersten Ziegel schief, wächst die Mauer schief bis zum Himmel.',
  },
  {
    id: 36,
    language: 'fa',
    proverb: 'خواهی نشوی رسوا، همرنگ جماعت شو',
    equivalent: 'Mit den Wölfen muss man heulen.',
    meaning:
      'Wer in einer Gruppe nicht unangenehm auffallen will, passt sich ihren Gewohnheiten an.',
    category: 'Alltag',
    note: 'Wörtlich: Willst du nicht bloßgestellt werden, nimm die Farbe der Menge an.',
  },
  {
    id: 37,
    language: 'fa',
    proverb: 'دیگ به دیگ می‌گوید رویت سیاه',
    equivalent: 'Der Topf nennt den Kessel schwarz.',
    meaning:
      'Jemand kritisiert bei anderen genau den Fehler, den er selbst besitzt.',
    category: 'Alltag',
    note: 'Wörtlich: Der Topf sagt zum anderen Topf: Dein Gesicht ist schwarz.',
  },
  {
    id: 38,
    language: 'fa',
    proverb: 'دوری و دوستی',
    equivalent: 'Gute Zäune machen gute Nachbarn.',
    meaning:
      'Ein gesunder Abstand und klare Grenzen können eine Beziehung bewahren.',
    category: 'Zusammenarbeit',
    note: 'Wörtlich: Abstand und Freundschaft.',
  },
  {
    id: 39,
    language: 'fa',
    proverb: 'دست بالای دست بسیار است',
    equivalent: 'Es gibt immer einen größeren Fisch.',
    meaning:
      'Wie mächtig oder geschickt jemand auch ist, es gibt meist noch jemanden, der ihn übertrifft.',
    category: 'Weisheit',
    note: 'Wörtlich: Über jeder Hand gibt es viele weitere Hände.',
  },
  {
    id: 40,
    language: 'fa',
    proverb: 'درِ دروازه را می‌شود بست، دهان مردم را نه',
    equivalent: 'Allen Leuten recht getan, ist eine Kunst, die niemand kann.',
    meaning:
      'Man kann nicht verhindern, dass andere reden und urteilen, und sollte sich nicht davon beherrschen lassen.',
    category: 'Alltag',
    note: 'Wörtlich: Das Stadttor kann man schließen, den Mund der Leute nicht.',
  },
  {
    id: 41,
    language: 'fa',
    proverb: 'دشمن دانا بلندت می‌کند، بر زمینت می‌زند نادان دوست',
    equivalent: 'Ein kluger Feind ist besser als ein dummer Freund.',
    meaning:
      'Kluge Kritik kann nützen, während gut gemeinte Hilfe eines Unverständigen großen Schaden anrichten kann.',
    category: 'Weisheit',
    note: 'Wörtlich: Ein kluger Feind hebt dich empor, ein törichter Freund wirft dich zu Boden.',
  },
  {
    id: 42,
    language: 'fa',
    proverb: 'رهرو آن است که آهسته و پیوسته رود',
    equivalent: 'Steter Tropfen höhlt den Stein.',
    meaning:
      'Beständigkeit und Ausdauer führen verlässlicher zum Ziel als ein kurzer, heftiger Einsatz.',
    category: 'Geduld',
    note: 'Wörtlich: Ein wahrer Wanderer geht langsam und ununterbrochen.',
  },
  {
    id: 43,
    language: 'fa',
    proverb: 'سالی که نکوست، از بهارش پیداست',
    equivalent: 'Ein guter Anfang ist die halbe Miete.',
    meaning:
      'Frühe Anzeichen lassen oft erkennen, wie sich eine Sache weiterentwickeln wird.',
    category: 'Weisheit',
    note: 'Wörtlich: Ein gutes Jahr erkennt man an seinem Frühling.',
  },
  {
    id: 44,
    language: 'fa',
    proverb: 'سنگ بزرگ نشانهٔ نزدن است',
    equivalent: 'Große Worte, nichts dahinter.',
    meaning:
      'Übertrieben große Versprechen sind oft ein Zeichen dafür, dass niemand ernsthaft handeln wird.',
    category: 'Alltag',
    note: 'Wörtlich: Ein zu großer Stein zeigt, dass man nicht werfen will.',
  },
  {
    id: 45,
    language: 'fa',
    proverb: 'شتر دیدی، ندیدی',
    equivalent: 'Reden ist Silber, Schweigen ist Gold.',
    meaning:
      'In einer heiklen Situation ist es manchmal sicherer, Gesehenes nicht weiterzuerzählen.',
    category: 'Weisheit',
    note: 'Wörtlich: Hast du ein Kamel gesehen? Du hast es nicht gesehen.',
  },
  {
    id: 46,
    language: 'fa',
    proverb: 'عجله کار شیطان است',
    equivalent: 'Eile mit Weile.',
    meaning:
      'Übereiltes Handeln führt leicht zu Fehlern; Sorgfalt ist wichtiger als Hast.',
    category: 'Geduld',
    note: 'Wörtlich: Hast ist das Werk des Teufels.',
  },
  {
    id: 47,
    language: 'fa',
    proverb: 'عاقل را اشارتی کافی است',
    equivalent: 'Dem Klugen genügt ein Wink.',
    meaning:
      'Ein verständiger Mensch begreift eine Botschaft, ohne dass man sie ausführlich erklären muss.',
    category: 'Weisheit',
    note: 'Wörtlich: Für den Klugen reicht ein Zeichen.',
  },
  {
    id: 48,
    language: 'fa',
    proverb: 'عدو شود سبب خیر، اگر خدا خواهد',
    equivalent: 'Jedes Unglück hat auch sein Gutes.',
    meaning:
      'Sogar eine feindliche Handlung kann unerwartet zu einem guten Ergebnis führen.',
    category: 'Weisheit',
    note: 'Wörtlich: Wenn Gott will, wird der Feind zur Ursache des Guten.',
  },
  {
    id: 49,
    language: 'fa',
    proverb: 'عیب می جمله بگفتی، هنرش نیز بگو',
    equivalent: 'Wo Schatten ist, ist auch Licht.',
    meaning:
      'Wer die Fehler eines Menschen nennt, sollte fairerweise auch seine guten Seiten erwähnen.',
    category: 'Weisheit',
    note: 'Wörtlich: Du hast alle Fehler des Weines genannt; nenne nun auch seine Vorzüge.',
  },
  {
    id: 50,
    language: 'fa',
    proverb: 'فلفل نبین چه ریزه، بشکن ببین چه تیزه',
    equivalent: 'Klein, aber oho.',
    meaning:
      'Größe und äußere Erscheinung sagen wenig über Kraft, Können oder Wirkung aus.',
    category: 'Alltag',
    note: 'Wörtlich: Sieh nicht, wie klein die Pfefferschote ist; brich sie und spüre ihre Schärfe.',
  },
  {
    id: 51,
    language: 'fa',
    proverb: 'کبوتر با کبوتر، باز با باز',
    equivalent: 'Gleich und Gleich gesellt sich gern.',
    meaning:
      'Menschen mit ähnlichen Eigenschaften und Interessen finden meist zueinander.',
    category: 'Zusammenarbeit',
    note: 'Wörtlich: Taube zu Taube, Falke zu Falke.',
  },
  {
    id: 52,
    language: 'fa',
    proverb: 'گر صبر کنی، ز غوره حلوا سازی',
    equivalent: 'Gut Ding will Weile haben.',
    meaning:
      'Mit Geduld kann aus einem unreifen Anfang etwas Reifes und Wertvolles entstehen.',
    category: 'Geduld',
    note: 'Wörtlich: Wenn du geduldig bist, machst du aus sauren Trauben schließlich Süßspeise.',
  },
  {
    id: 53,
    language: 'fa',
    proverb: 'گرهی که با دست باز می‌شود، با دندان باز نکن',
    equivalent: 'Nicht mit Kanonen auf Spatzen schießen.',
    meaning:
      'Ein einfaches Problem sollte mit einem einfachen, angemessenen Mittel gelöst werden.',
    category: 'Arbeit',
    note: 'Wörtlich: Öffne einen Knoten, den die Hand lösen kann, nicht mit den Zähnen.',
  },
  {
    id: 54,
    language: 'fa',
    proverb: 'گربه دستش به گوشت نمی‌رسد، می‌گوید بو می‌دهد',
    equivalent: 'Die Trauben sind zu sauer.',
    meaning:
      'Wer etwas Unerreichbares nicht bekommen kann, redet dessen Wert oft absichtlich klein.',
    category: 'Alltag',
    note: 'Wörtlich: Die Katze erreicht das Fleisch nicht und behauptet, es rieche schlecht.',
  },
  {
    id: 55,
    language: 'fa',
    proverb: 'گل بود، به سبزه نیز آراسته شد',
    equivalent: 'Ein Unglück kommt selten allein.',
    meaning:
      'Zu einer bereits schwierigen Lage kommt noch eine weitere Komplikation hinzu.',
    category: 'Alltag',
    note: 'Wörtlich: Es war schon eine Blume und wurde nun auch noch mit Grün geschmückt; meist ironisch gemeint.',
  },
  {
    id: 56,
    language: 'fa',
    proverb: 'ماهی را هر وقت از آب بگیری تازه است',
    equivalent: 'Besser spät als nie.',
    meaning:
      'Für eine richtige Entscheidung oder eine Verbesserung ist es selten vollständig zu spät.',
    category: 'Gelegenheit',
    note: 'Wörtlich: Wann immer du den Fisch aus dem Wasser holst, ist er frisch.',
  },
  {
    id: 57,
    language: 'fa',
    proverb: 'مارگزیده از ریسمان سیاه و سفید می‌ترسد',
    equivalent: 'Gebranntes Kind scheut das Feuer.',
    meaning:
      'Nach einer schlechten Erfahrung wird man selbst bei harmlosen Ähnlichkeiten besonders vorsichtig.',
    category: 'Weisheit',
    note: 'Wörtlich: Wer von einer Schlange gebissen wurde, fürchtet selbst ein schwarz-weißes Seil.',
  },
  {
    id: 58,
    language: 'fa',
    proverb: 'موش توی سوراخ نمی‌رفت، جارو به دمش می‌بست',
    equivalent: 'Mehr aufladen, als man tragen kann.',
    meaning:
      'Jemand erschwert seine ohnehin schwierige Lage durch eine zusätzliche, unnötige Belastung.',
    category: 'Alltag',
    note: 'Wörtlich: Die Maus passte nicht ins Loch und band sich noch einen Besen an den Schwanz.',
  },
  {
    id: 59,
    language: 'fa',
    proverb: 'نرود میخ آهنین در سنگ',
    equivalent: 'Gegen Dummheit kämpfen Götter selbst vergebens.',
    meaning:
      'Bei einem völlig unzugänglichen Menschen helfen selbst klare Argumente und große Mühe nicht.',
    category: 'Weisheit',
    note: 'Wörtlich: Ein eiserner Nagel dringt nicht in Stein.',
  },
  {
    id: 60,
    language: 'fa',
    proverb: 'هر که بامش بیش، برفش بیشتر',
    equivalent: 'Viel Besitz, viel Sorge.',
    meaning:
      'Mit größerem Besitz und höherer Stellung wachsen auch Verantwortung und Probleme.',
    category: 'Alltag',
    note: 'Wörtlich: Wer das größere Dach hat, bekommt mehr Schnee.',
  },
  {
    id: 61,
    language: 'fa',
    proverb: 'هر که طاووس خواهد، جور هندوستان کشد',
    equivalent: 'Wer schön sein will, muss leiden.',
    meaning:
      'Wer etwas Besonderes erreichen oder besitzen will, muss die damit verbundene Mühe tragen.',
    category: 'Arbeit',
    note: 'Wörtlich: Wer den Pfau will, muss die Mühsal Indiens ertragen.',
  },
  {
    id: 62,
    language: 'fa',
    proverb: 'هر گردی گردو نیست',
    equivalent: 'Es ist nicht alles Gold, was glänzt.',
    meaning:
      'Äußerliche Ähnlichkeit oder schöner Schein beweisen noch keinen echten Wert.',
    category: 'Weisheit',
    note: 'Wörtlich: Nicht alles Runde ist eine Walnuss.',
  },
  {
    id: 63,
    language: 'fa',
    proverb: 'هنوز دهانش بوی شیر می‌دهد',
    equivalent: 'Er ist noch grün hinter den Ohren.',
    meaning:
      'Jemand ist noch sehr jung und verfügt über wenig Lebenserfahrung.',
    category: 'Alltag',
    note: 'Wörtlich: Sein Mund riecht noch nach Milch.',
  },
  {
    id: 64,
    language: 'fa',
    proverb: 'یک سوزن به خودت بزن، یک جوالدوز به مردم',
    equivalent: 'Kehre zuerst vor deiner eigenen Tür.',
    meaning:
      'Bevor man andere hart kritisiert, sollte man die eigenen Fehler ehrlich prüfen.',
    category: 'Weisheit',
    note: 'Wörtlich: Stich dich selbst mit einer Nadel, bevor du andere mit einer Sacknadel stichst.',
  },
  {
    id: 65,
    language: 'fa',
    proverb: 'یک کلاغ، چهل کلاغ کردن',
    equivalent: 'Aus einer Mücke einen Elefanten machen.',
    meaning:
      'Eine kleine Nachricht wird beim Weitererzählen stark übertrieben und aufgebauscht.',
    category: 'Alltag',
    note: 'Wörtlich: Aus einer Krähe vierzig Krähen machen.',
  },
  {
    id: 66,
    language: 'fa',
    proverb: 'پایت را از گلیمت درازتر نکن',
    equivalent: 'Man soll nicht über seine Verhältnisse leben.',
    meaning:
      'Man sollte seine Ausgaben und Ansprüche an die eigenen Möglichkeiten anpassen.',
    category: 'Alltag',
    note: 'Wörtlich: Strecke deine Füße nicht weiter aus als deinen Teppich.',
  },
  {
    id: 67,
    language: 'de',
    proverb: 'Aller Anfang ist schwer.',
    equivalent: 'شروع هر کاری سخت است',
    meaning: 'آغاز یک کار تازه معمولاً به تلاش، یادگیری و پشتکار بیشتری نیاز دارد.',
    category: 'کار',
    note: 'ترجمهٔ لفظی: هر آغازی دشوار است.',
  },
  {
    id: 68,
    language: 'de',
    proverb: 'Andere Länder, andere Sitten.',
    equivalent: 'هر دیاری رسم و آیین خود را دارد',
    meaning: 'فرهنگ‌ها و سرزمین‌های مختلف، عادت‌ها و قواعد متفاوتی دارند.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: کشورهای دیگر، رسم‌های دیگر.',
  },
  {
    id: 69,
    language: 'de',
    proverb: 'Aus den Augen, aus dem Sinn.',
    equivalent: 'از دل برود هر آن‌که از دیده برفت',
    meaning: 'وقتی کسی یا چیزی برای مدتی دیده نشود، ممکن است کم‌کم فراموش شود.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: دور از چشم، دور از ذهن.',
  },
  {
    id: 70,
    language: 'de',
    proverb: 'Besser den Spatz in der Hand als die Taube auf dem Dach.',
    equivalent: 'سیلی نقد به از حلوای نسیه',
    meaning: 'سود کوچک اما قطعی، بهتر از سود بزرگ و نامطمئن در آینده است.',
    category: 'اراده',
    note: 'ترجمهٔ لفظی: گنجشک در دست بهتر از کبوتر روی بام است.',
  },
  {
    id: 71,
    language: 'de',
    proverb: 'Besser ein Ende mit Schrecken als ein Schrecken ohne Ende.',
    equivalent: 'مرگ یک بار، شیون یک بار',
    meaning: 'پایان سخت اما قطعی، بهتر از ادامه یافتن یک وضعیت دردناک و بی‌پایان است.',
    category: 'اراده',
    note: 'ترجمهٔ لفظی: پایانی هولناک بهتر از هراسی بی‌پایان است.',
  },
  {
    id: 72,
    language: 'de',
    proverb: 'Blut ist dicker als Wasser.',
    equivalent: 'گوشت هم را بخورد، استخوان هم را دور نمی‌اندازد',
    meaning: 'پیوند خانوادگی معمولاً حتی پس از اختلاف و دعوا همچنان پابرجا می‌ماند.',
    category: 'خانواده',
    note: 'ترجمهٔ لفظی: خون از آب غلیظ‌تر است.',
  },
  {
    id: 73,
    language: 'de',
    proverb: 'Der frühe Vogel fängt den Wurm.',
    equivalent: 'سحرخیز باش تا کامروا باشی',
    meaning: 'کسی که زود و به‌موقع شروع کند، شانس بیشتری برای موفقیت دارد.',
    category: 'کار',
    note: 'ترجمهٔ لفظی: پرندهٔ سحرخیز کرم را می‌گیرد.',
  },
  {
    id: 74,
    language: 'de',
    proverb: 'Doppelt genäht hält besser.',
    equivalent: 'احتیاط شرط عقل است',
    meaning: 'اطمینان و بررسی دوباره می‌تواند از خطا و خسارت جلوگیری کند.',
    category: 'کار',
    note: 'ترجمهٔ لفظی: چیزی که دوبار دوخته شود، محکم‌تر می‌ماند.',
  },
  {
    id: 75,
    language: 'de',
    proverb: 'Ein gebranntes Kind scheut das Feuer.',
    equivalent: 'مارگزیده از ریسمان سیاه و سفید می‌ترسد',
    meaning: 'کسی که تجربهٔ بدی داشته باشد، بعد از آن حتی از نشانه‌های مشابه هم می‌ترسد.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: کودک سوخته از آتش دوری می‌کند.',
  },
  {
    id: 76,
    language: 'de',
    proverb: 'Ein Unglück kommt selten allein.',
    equivalent: 'گل بود، به سبزه نیز آراسته شد',
    meaning: 'گاهی پس از یک مشکل، گرفتاری دیگری هم به آن اضافه می‌شود.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: بدبختی به‌ندرت تنها می‌آید.',
  },
  {
    id: 77,
    language: 'de',
    proverb: 'Ende gut, alles gut.',
    equivalent: 'شاهنامه آخرش خوش است',
    meaning: 'اگر نتیجهٔ نهایی خوب باشد، سختی‌ها و مشکلات راه آسان‌تر فراموش می‌شوند.',
    category: 'اراده',
    note: 'ترجمهٔ لفظی: پایان خوب، همه‌چیز خوب.',
  },
  {
    id: 78,
    language: 'de',
    proverb: 'Erst die Arbeit, dann das Vergnügen.',
    equivalent: 'اول کار، بعد استراحت',
    meaning: 'وظیفه و مسئولیت باید پیش از تفریح و آسایش انجام شود.',
    category: 'کار',
    note: 'ترجمهٔ لفظی: نخست کار، سپس لذت.',
  },
  {
    id: 79,
    language: 'de',
    proverb: 'Geben ist seliger denn Nehmen.',
    equivalent: 'دست دهنده بهتر از دست گیرنده است',
    meaning: 'بخشندگی و کمک به دیگران ارزشمندتر از تنها دریافت کردن است.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: دادن خجسته‌تر از گرفتن است.',
  },
  {
    id: 80,
    language: 'de',
    proverb: 'Gelegenheit macht Diebe.',
    equivalent: 'مال بی‌صاحب، صاحبش را دزد می‌کند',
    meaning: 'نبود مراقبت و فراهم بودن موقعیت می‌تواند انسان را به کار نادرست وسوسه کند.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: فرصت، دزد می‌سازد.',
  },
  {
    id: 81,
    language: 'de',
    proverb: 'Geteiltes Leid ist halbes Leid.',
    equivalent: 'غم اگر قسمت شود، سبک‌تر می‌شود',
    meaning: 'صحبت کردن با دیگران و شریک شدن در اندوه، تحمل آن را آسان‌تر می‌کند.',
    category: 'خانواده',
    note: 'ترجمهٔ لفظی: رنج تقسیم‌شده، نصف رنج است.',
  },
  {
    id: 82,
    language: 'de',
    proverb: 'Geteilte Freude ist doppelte Freude.',
    equivalent: 'شادیِ تقسیم‌شده دوچندان می‌شود',
    meaning: 'شادی هنگامی که با دیگران شریک می‌شود، ارزش و لذت بیشتری پیدا می‌کند.',
    category: 'خانواده',
    note: 'ترجمهٔ لفظی: شادی تقسیم‌شده، شادی دوبرابر است.',
  },
  {
    id: 83,
    language: 'de',
    proverb: 'Gleich und Gleich gesellt sich gern.',
    equivalent: 'کبوتر با کبوتر، باز با باز',
    meaning: 'آدم‌هایی با ویژگی‌ها و علاقه‌های مشابه معمولاً یکدیگر را پیدا می‌کنند.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: همانندها با میل کنار هم می‌نشینند.',
  },
  {
    id: 84,
    language: 'de',
    proverb: 'Hochmut kommt vor dem Fall.',
    equivalent: 'فواره چون بلند شود، سرنگون شود',
    meaning: 'غرور و خودبزرگ‌بینی اغلب پیش از شکست و سقوط ظاهر می‌شود.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: تکبر پیش از سقوط می‌آید.',
  },
  {
    id: 85,
    language: 'de',
    proverb: 'Hunde, die bellen, beißen nicht.',
    equivalent: 'سگی که پارس می‌کند، گاز نمی‌گیرد',
    meaning: 'کسانی که بسیار تهدید می‌کنند، همیشه خطرناک‌ترین افراد نیستند.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی دو عبارت در هر دو زبان تقریباً یکسان است.',
  },
  {
    id: 86,
    language: 'de',
    proverb: 'Irren ist menschlich.',
    equivalent: 'انسان جایزالخطاست',
    meaning: 'اشتباه کردن بخشی طبیعی از زندگی و تجربهٔ انسان است.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: خطا کردن انسانی است.',
  },
  {
    id: 87,
    language: 'de',
    proverb: 'Jeder Topf findet seinen Deckel.',
    equivalent: 'هر کسی جفتی دارد',
    meaning: 'برای هر انسان معمولاً فردی مناسب با روحیه و ویژگی‌های او پیدا می‌شود.',
    category: 'خانواده',
    note: 'ترجمهٔ لفظی: هر قابلمه‌ای درِ خودش را پیدا می‌کند.',
  },
  {
    id: 88,
    language: 'de',
    proverb: 'Keine Antwort ist auch eine Antwort.',
    equivalent: 'سکوت هم خودش یک جواب است',
    meaning: 'پاسخ ندادن نیز می‌تواند موضع و نظر یک شخص را روشن کند.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی دو عبارت تقریباً یکسان است.',
  },
  {
    id: 89,
    language: 'de',
    proverb: 'Keine Rose ohne Dornen.',
    equivalent: 'گل بی‌خار نیست',
    meaning: 'هیچ چیز زیبا یا ارزشمندی کاملاً بدون دشواری و عیب نیست.',
    category: 'اراده',
    note: 'ترجمهٔ لفظی: هیچ گلی بدون خار نیست.',
  },
  {
    id: 90,
    language: 'de',
    proverb: 'Kleider machen Leute.',
    equivalent: 'مردم از روی لباس قضاوت می‌کنند',
    meaning: 'ظاهر و پوشش بر برداشت نخست دیگران از یک فرد تأثیر زیادی دارد.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: لباس‌ها آدم‌ها را می‌سازند.',
  },
  {
    id: 91,
    language: 'de',
    proverb: 'Kleine Ursache, große Wirkung.',
    equivalent: 'یک جرقه، جنگلی را می‌سوزاند',
    meaning: 'یک اتفاق یا اشتباه کوچک می‌تواند پیامدهای بسیار بزرگی داشته باشد.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: علت کوچک، اثر بزرگ.',
  },
  {
    id: 92,
    language: 'de',
    proverb: 'Lachen ist die beste Medizin.',
    equivalent: 'خنده بر هر درد بی‌درمان دواست',
    meaning: 'شاد بودن و خندیدن می‌تواند حال روحی انسان را بهتر کند.',
    category: 'خانواده',
    note: 'ترجمهٔ لفظی: خنده بهترین دارو است.',
  },
  {
    id: 93,
    language: 'de',
    proverb: 'Leben und leben lassen.',
    equivalent: 'زندگی کن و بگذار دیگران هم زندگی کنند',
    meaning: 'به شیوهٔ زندگی دیگران احترام بگذار و بی‌دلیل در کارشان دخالت نکن.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی دو عبارت یکسان است.',
  },
  {
    id: 94,
    language: 'de',
    proverb: 'Liebe macht blind.',
    equivalent: 'عشق آدم را کور می‌کند',
    meaning: 'عشق می‌تواند باعث شود عیب‌ها و واقعیت‌های ناخوشایند را نبینیم.',
    category: 'خانواده',
    note: 'ترجمهٔ لفظی دو عبارت یکسان است.',
  },
  {
    id: 95,
    language: 'de',
    proverb: 'Man erntet, was man sät.',
    equivalent: 'گندم از گندم بروید، جو ز جو',
    meaning: 'نتیجهٔ رفتار و تلاش انسان معمولاً با آنچه انجام داده متناسب است.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: انسان همان چیزی را درو می‌کند که کاشته است.',
  },
  {
    id: 96,
    language: 'de',
    proverb: 'Morgenstund hat Gold im Mund.',
    equivalent: 'سحرخیز باش تا کامروا باشی',
    meaning: 'شروع زودهنگام روز فرصت و آمادگی بیشتری برای موفقیت فراهم می‌کند.',
    category: 'کار',
    note: 'ترجمهٔ لفظی: ساعت صبح در دهانش طلا دارد.',
  },
  {
    id: 97,
    language: 'de',
    proverb: 'Not macht erfinderisch.',
    equivalent: 'احتیاج مادر اختراع است',
    meaning: 'نیاز و دشواری انسان را وادار می‌کند راه‌حل‌های تازه و خلاقانه پیدا کند.',
    category: 'کار',
    note: 'ترجمهٔ لفظی: نیاز، انسان را مبتکر می‌کند.',
  },
  {
    id: 98,
    language: 'de',
    proverb: 'Probieren geht über Studieren.',
    equivalent: 'شنیدن کی بود مانند دیدن',
    meaning: 'تجربهٔ عملی گاهی بیشتر از مطالعه و توضیح نظری به انسان می‌آموزد.',
    category: 'کار',
    note: 'ترجمهٔ لفظی: امتحان کردن از مطالعه بالاتر است.',
  },
  {
    id: 99,
    language: 'de',
    proverb: 'Rom ist nicht an einem Tag erbaut worden.',
    equivalent: 'گر صبر کنی، ز غوره حلوا سازی',
    meaning: 'کارهای بزرگ برای کامل شدن به زمان، صبر و تلاش پیوسته نیاز دارند.',
    category: 'اراده',
    note: 'ترجمهٔ لفظی: شهر رم در یک روز ساخته نشده است.',
  },
  {
    id: 100,
    language: 'de',
    proverb: 'Stille Wasser sind tief.',
    equivalent: 'آب‌های آرام عمیق‌اند',
    meaning: 'آدم‌های آرام و کم‌حرف ممکن است اندیشه و توانایی عمیقی داشته باشند.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: آب‌های ساکت عمیق‌اند.',
  },
  {
    id: 101,
    language: 'de',
    proverb: 'Unverhofft kommt oft.',
    equivalent: 'اتفاق خبر نمی‌کند',
    meaning: 'رویدادهای غیرمنتظره بیش از آنچه تصور می‌کنیم رخ می‌دهند.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: چیز غیرمنتظره اغلب از راه می‌رسد.',
  },
  {
    id: 102,
    language: 'de',
    proverb: 'Viele Wege führen nach Rom.',
    equivalent: 'برای رسیدن به مقصد راه بسیار است',
    meaning: 'برای حل یک مسئله یا رسیدن به یک هدف تنها یک روش وجود ندارد.',
    category: 'کار',
    note: 'ترجمهٔ لفظی: راه‌های بسیاری به رم می‌رسند.',
  },
  {
    id: 103,
    language: 'de',
    proverb: 'Vorsicht ist die Mutter der Porzellankiste.',
    equivalent: 'احتیاط شرط عقل است',
    meaning: 'دقت و احتیاط از آسیب و اشتباه‌های قابل پیشگیری جلوگیری می‌کند.',
    category: 'کار',
    note: 'ترجمهٔ لفظی: احتیاط مادر جعبهٔ چینی است.',
  },
  {
    id: 104,
    language: 'de',
    proverb: 'Was Hänschen nicht lernt, lernt Hans nimmermehr.',
    equivalent: 'درخت را تا جوان است باید راست کرد',
    meaning: 'آموختن و شکل دادن عادت‌های خوب در کودکی بسیار آسان‌تر است.',
    category: 'خانواده',
    note: 'ترجمهٔ لفظی: آنچه هانس کوچک نیاموزد، هانس بزرگ دیگر نمی‌آموزد.',
  },
  {
    id: 105,
    language: 'de',
    proverb: 'Was sich liebt, das neckt sich.',
    equivalent: 'دعوا نمک زندگی است',
    meaning: 'شوخی و سربه‌سر گذاشتن گاهی می‌تواند نشانهٔ صمیمیت و علاقه باشد.',
    category: 'خانواده',
    note: 'ترجمهٔ لفظی: کسانی که همدیگر را دوست دارند، یکدیگر را دست می‌اندازند.',
  },
  {
    id: 106,
    language: 'de',
    proverb: 'Wenn zwei sich streiten, freut sich der Dritte.',
    equivalent: 'جنگ دو نفر، سود نفر سوم است',
    meaning: 'اختلاف میان دو نفر ممکن است فرصت و منفعتی برای شخص دیگری ایجاد کند.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: وقتی دو نفر دعوا می‌کنند، نفر سوم خوشحال می‌شود.',
  },
  {
    id: 107,
    language: 'de',
    proverb: 'Wer A sagt, muss auch B sagen.',
    equivalent: 'کار را که کرد، آن که تمام کرد',
    meaning: 'کسی که کاری را آغاز می‌کند، باید مسئولیت ادامه و پایان آن را نیز بپذیرد.',
    category: 'اراده',
    note: 'ترجمهٔ لفظی: کسی که الف می‌گوید، باید ب هم بگوید.',
  },
  {
    id: 108,
    language: 'de',
    proverb: 'Wer im Glashaus sitzt, soll nicht mit Steinen werfen.',
    equivalent: 'یک سوزن به خودت بزن، یک جوالدوز به مردم',
    meaning: 'کسی که خودش عیب دارد، نباید دیگران را با سخت‌گیری سرزنش کند.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: کسی که در خانهٔ شیشه‌ای نشسته، نباید سنگ پرتاب کند.',
  },
  {
    id: 109,
    language: 'de',
    proverb: 'Wer zuletzt lacht, lacht am besten.',
    equivalent: 'جوجه را آخر پاییز می‌شمارند',
    meaning: 'نتیجهٔ نهایی مهم است و نباید پیش از پایان کار دربارهٔ موفقیت قضاوت کرد.',
    category: 'اراده',
    note: 'ترجمهٔ لفظی: کسی که آخر می‌خندد، بهتر می‌خندد.',
  },
  {
    id: 110,
    language: 'de',
    proverb: 'Wo gehobelt wird, da fallen Späne.',
    equivalent: 'هر کاری هزینه‌ای دارد',
    meaning: 'انجام کارهای بزرگ معمولاً بدون پیامدهای کوچک یا اشتباه‌های فرعی ممکن نیست.',
    category: 'کار',
    note: 'ترجمهٔ لفظی: جایی که رنده می‌کنند، پوشال هم می‌ریزد.',
  },
  {
    id: 111,
    language: 'de',
    proverb: 'Zeit heilt alle Wunden.',
    equivalent: 'گذر زمان مرهم زخم‌هاست',
    meaning: 'با گذشت زمان، شدت بسیاری از اندوه‌ها و آسیب‌های روحی کمتر می‌شود.',
    category: 'اراده',
    note: 'ترجمهٔ لفظی دو عبارت تقریباً یکسان است.',
  },
  {
    id: 112,
    language: 'de',
    proverb: 'Zeit ist Geld.',
    equivalent: 'وقت طلاست',
    meaning: 'زمان ارزشمند است و نباید آن را بیهوده از دست داد.',
    category: 'کار',
    note: 'ترجمهٔ لفظی: زمان پول است؛ در فارسی زمان به طلا تشبیه می‌شود.',
  },
  {
    id: 113,
    language: 'de',
    proverb: 'Zu viele Köche verderben den Brei.',
    equivalent: 'آشپز که دو تا شد، آش یا شور می‌شود یا بی‌نمک',
    meaning: 'وقتی افراد زیادی بدون هماهنگی مسئول یک کار باشند، نتیجه معمولاً ضعیف می‌شود.',
    category: 'کار',
    note: 'ترجمهٔ لفظی: آشپزهای زیاد حریره را خراب می‌کنند.',
  },
  {
    id: 114,
    language: 'de',
    proverb: 'Der Schein trügt.',
    equivalent: 'هر گردی گردو نیست',
    meaning: 'ظاهر یک چیز یا یک شخص همیشه حقیقت و ارزش واقعی آن را نشان نمی‌دهد.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: ظاهر فریب می‌دهد.',
  },
  {
    id: 115,
    language: 'de',
    proverb: 'Wer nicht wagt, der nicht gewinnt.',
    equivalent: 'نابرده رنج، گنج میسر نمی‌شود',
    meaning: 'بدون پذیرفتن سختی یا خطر حساب‌شده، رسیدن به موفقیت بزرگ دشوار است.',
    category: 'اراده',
    note: 'ترجمهٔ لفظی: کسی که خطر نمی‌کند، چیزی به دست نمی‌آورد.',
  },
  {
    id: 116,
    language: 'de',
    proverb: 'Was lange währt, wird endlich gut.',
    equivalent: 'گر صبر کنی، ز غوره حلوا سازی',
    meaning: 'کاری که با صبر و زمان کافی ادامه یابد، سرانجام می‌تواند نتیجهٔ خوبی بدهد.',
    category: 'اراده',
    note: 'ترجمهٔ لفظی: آنچه مدت زیادی طول بکشد، سرانجام خوب می‌شود.',
  },
];
