import { siteUrl } from './seo-content';
export type Locale = 'de' | 'fa';
export function localizedPath(locale: Locale, path='') { return `/${locale}${path === '/' ? '' : path}`; }
export function languageAlternates(path='') { return {de:siteUrl+localizedPath('de',path),fa:siteUrl+localizedPath('fa',path),'x-default':siteUrl+localizedPath('de',path)}; }
export const ui = {
  de: { home:'Sammlung', lessons:'Lernprobe', about:'Lesehilfe & Über uns', skip:'Zum Inhalt', nav:'Hauptnavigation', search:'Sprichwörter durchsuchen', placeholder:'Deutsch, Persisch oder Umschrift …', all:'Alle Themen', sort:'Sortierung', original:'Reihenfolge der Sammlung', alphabet:'Alphabetisch nach Persisch', found:'Einträge', empty:'Noch nichts gefunden', emptyText:'Versuche ein anderes Wort oder setze die Filter zurück.', reset:'Suche zurücksetzen', meaning:'Bedeutung', example:'Beispiel aus dem Alltag', equivalent:'Deutsche Entsprechung', source:'Persisches Sprichwort', pronunciation:'Deutsche Aussprachehilfe', open:'Bedeutung & Beispiel öffnen', more:'Weitere Sprichwörter', title:'Persisch lernen mit Sprichwörtern', lead:'Entdecke persische Sprichwörter mit deutscher Aussprachehilfe, verständlichen Bedeutungen und Beispielen. Schritt für Schritt lernst du, wann sie im Alltag passen.', topics:'Nach Thema entdecken', topicTitle:'Persische Sprichwörter über', aboutTitle:'So lernst du mit Zarbol Masal', practiceTitle:'Persische Sprichwörter üben', practiceLead:'Fünf Sprichwörter kennenlernen und mit kurzen Aufgaben üben. Kostenlos, ohne Anmeldung und zum Ausdrucken.', print:'Lernprobe drucken / als PDF speichern', right:'Richtig.', wrong:'Noch nicht ganz. Lies das Beispiel erneut und versuche die andere Antwort.', progress:'von 5 Übungen bearbeitet', score:'von 5 Antworten richtig', restart:'Übungen zurücksetzen', context:'Einordnung', solutions:'Lösungen', question:'Übung', footer:'Persisch lernen. Sprichwörter verstehen.', notFound:'Diese Seite wurde nicht gefunden', back:'Zur Sammlung', method:'Die Beispiele wurden für diese Lernsammlung formuliert. Die Entsprechungen sind sinngemäß.', learnMore:'Mehr zur Sammlung', free:'Kostenlose Lernprobe', language:'Sprache wählen' },
  fa: { home:'مجموعه', lessons:'تمرین رایگان', about:'راهنما و دربارهٔ ما', skip:'رفتن به محتوا', nav:'منوی اصلی', search:'جست‌وجوی ضرب‌المثل‌ها', placeholder:'واژه‌ای به آلمانی یا فارسی بنویسید…', all:'همهٔ موضوع‌ها', sort:'مرتب‌سازی', original:'ترتیب مجموعه', alphabet:'به ترتیب الفبای آلمانی', found:'مورد', empty:'نتیجه‌ای پیدا نشد', emptyText:'واژهٔ دیگری را امتحان کنید یا فیلترها را پاک کنید.', reset:'پاک کردن جست‌وجو', meaning:'معنی', example:'مثال روزمره', equivalent:'معادل فارسی', source:'ضرب‌المثل آلمانی', pronunciation:'راهنمای تلفظ', open:'معنی و مثال را بخوانید', more:'ضرب‌المثل‌های بیشتر', title:'آلمانی را با ضرب‌المثل‌ها یاد بگیرید', lead:'ضرب‌المثل‌های آلمانی را با معنی فارسی و مثال‌های کاربردی یاد بگیرید. معادل فارسی به شما کمک می‌کند مفهوم و موقعیت استفاده از هر عبارت را بهتر بفهمید.', topics:'انتخاب موضوع', topicTitle:'ضرب‌المثل‌های آلمانی دربارهٔ', aboutTitle:'راهنمای یادگیری با ضرب‌المثل', practiceTitle:'تمرین ضرب‌المثل‌های آلمانی', practiceLead:'پنج ضرب‌المثل آلمانی را با توضیح فارسی و پرسش‌های کوتاه تمرین کنید. رایگان، بدون ثبت‌نام و قابل چاپ.', print:'چاپ تمرین / ذخیره به صورت PDF', right:'درست است.', wrong:'هنوز درست نیست. مثال را دوباره بخوانید و پاسخ دیگر را امتحان کنید.', progress:'تمرین از ۵ تمرین انجام شده است', score:'پاسخ از ۵ پاسخ درست است', restart:'شروع دوبارهٔ تمرین‌ها', context:'توضیح کاربرد', solutions:'پاسخ‌ها', question:'تمرین', footer:'آلمانی یاد بگیرید و ضرب‌المثل‌ها را بفهمید.', notFound:'این صفحه پیدا نشد', back:'بازگشت به مجموعه', method:'مثال‌ها برای این مجموعهٔ آموزشی نوشته شده‌اند. معادل‌ها بر اساس معنی انتخاب شده‌اند و ترجمهٔ کلمه‌به‌کلمه نیستند.', learnMore:'دربارهٔ این مجموعه', free:'تمرین رایگان', language:'انتخاب زبان' },
} as const;
export const topicDescriptionsFa:Record<string,string>={
 geduld:'این ضرب‌المثل‌ها دربارهٔ صبر و پشتکار هستند. عبارت آلمانی، معنی فارسی و مثال روزمره به شما کمک می‌کنند کاربرد هر کدام را یاد بگیرید.',
 weisheit:'با این ضرب‌المثل‌های آلمانی دربارهٔ تجربه، قضاوت و خرد آشنا شوید. معنی فارسی و مثال‌ها به درک بهتر موقعیت استفاده کمک می‌کنند.',
 arbeit:'ضرب‌المثل‌های آلمانی دربارهٔ کار، تمرین و تلاش را با معنی فارسی و مثال‌های کاربردی یاد بگیرید.',
 zusammenarbeit:'همکاری گاهی کارها را آسان‌تر می‌کند و گاهی دخالت زیاد نتیجه را خراب می‌کند. این عبارت‌های آلمانی هر دو جنبه را نشان می‌دهند.',
 alltag:'ضرب‌المثل‌های آلمانی دربارهٔ عادت‌ها، تصمیم‌ها و تجربه‌های روزمره را با توضیح فارسی بخوانید.',
 gelegenheit:'چه زمانی باید دست به کار شد؟ این ضرب‌المثل‌های آلمانی دربارهٔ فرصت‌ها به شما در یادگیری عبارت‌های کاربردی کمک می‌کنند.',
};
