import type {Locale} from './i18n';
import {ui,localizedPath,topicDescriptionsFa} from './i18n';
import {canonicalProverbs,proverbPath,topicPath,topics} from './seo-content';
import type {Proverb} from './additional-proverbs';
import {proverbLearning} from './proverb-learning';
import {pronunciationGuideDe} from './pronunciation';
import photos from './proverb-photos.json';
import LocalizedCollection from '@/components/localized-collection';
import LocalizedLessons from '@/components/localized-lessons';
import GermanAboutContent from '@/components/german-about-content';
import InterestForm from '@/components/interest-form';

export function CollectionPage({locale}:{locale:Locale}){const t=ui[locale];return <><section className="locale-intro"><h1>{t.title}</h1><p>{t.lead}</p><nav aria-label={t.topics}><ul className="topic-nav">{topics.map(topic=><li key={topic.slug}><a href={localizedPath(locale,`/themen/${topic.slug}`)}>{locale==='fa'?topic.fa:topic.name}</a></li>)}</ul></nav><a className="learning-text-link" href={localizedPath(locale,'/lernpaket')}>{t.free}</a></section><LocalizedCollection locale={locale}/></>;}

export function DetailPage({locale,p}:{locale:Locale;p:Proverb}){
 const fa=locale==='fa';const t=ui[locale];const l=proverbLearning[p.id];const topic=topics.find(t=>t.name===p.category)!;const photo=(photos as Record<string,Record<Locale,{src:string;alt:string}>>)[p.id]?.[locale];
 return <><nav className="content-breadcrumbs" aria-label={fa?'مسیر صفحه':'Brotkrumennavigation'}><a href={localizedPath(locale)}>{t.home}</a><span>/</span><a href={localizedPath(locale,topicPath(p.category))}>{fa?topic.fa:topic.name}</a></nav>
 <article><p className="locale-label">{t.source}</p><h1 lang={fa?'de':'fa'} dir={fa?'ltr':'rtl'}>{fa?p.equivalent:p.proverb}</h1>
 {photo&&<figure className="proverb-detail-photo"><img src={photo.src} alt={photo.alt} width={960} height={640}/><figcaption>{fa?'تصویر یادآور واژه‌های ضرب‌المثل':'Merkbild zum Wortlaut des Sprichworts'}</figcaption></figure>}
 {!fa&&<section className="content-panel"><h2>{t.pronunciation}</h2><p className="content-latin" lang="fa-Latn" dir="ltr">{l.latin}</p><details><summary>Hinweise zur Aussprache</summary><p>{pronunciationGuideDe}</p><a href="/de/ueber-die-sammlung#umschrift">Lesehilfe und Quellen</a></details></section>}
 <section><h2>{t.meaning}</h2><p className="content-lead">{fa?l.meaningFa:p.meaning}</p>{!fa&&<p>{p.note}</p>}</section>
 <section><h2>{t.equivalent}</h2><blockquote>{fa?p.proverb:p.equivalent}</blockquote><p>{fa?'این عبارت فارسی مفهوم مشابهی دارد. تصویر و لحن آن ممکن است با عبارت آلمانی متفاوت باشد؛ بنابراین معادل فارسی را ترجمهٔ دقیق واژه‌به‌واژه ندانید.':'Die deutsche Entsprechung vermittelt eine ähnliche Idee. Bild und Ton können abweichen; sie ist keine Wort-für-Wort-Übersetzung.'}</p></section>
 <section><h2>{t.example}</h2>{fa&&<p lang="de" dir="ltr">{l.exampleDe}</p>}<p>{fa?l.exampleFa:l.exampleDe}</p></section><p className="content-method">{t.method} <a href={localizedPath(locale,'/ueber-die-sammlung')}>{t.learnMore}</a></p></article>
 <section><h2>{t.more}</h2><ul className="content-links">{canonicalProverbs.filter(other=>other.category===p.category&&other.id!==p.id).slice(0,4).map(other=><li key={other.id}><a href={localizedPath(locale,proverbPath(other))} lang={fa?'de':'fa'} dir={fa?'ltr':'rtl'}>{fa?other.equivalent:other.proverb}</a></li>)}</ul></section><a className="learning-button no-print" href={localizedPath(locale,'/lernpaket')}>{t.free}</a></>;
}

export function TopicPage({locale,slug}:{locale:Locale;slug:string}){const topic=topics.find(t=>t.slug===slug)!;const fa=locale==='fa';const t=ui[locale];return <><nav className="content-breadcrumbs"><a href={localizedPath(locale)}>{t.home}</a></nav><h1>{t.topicTitle} {fa?topic.fa:topic.name}</h1><p className="content-lead">{fa?topicDescriptionsFa[slug]:topic.description}</p><ul className="topic-entries">{canonicalProverbs.filter(p=>p.category===topic.name).map(p=><li key={p.id}><h2 lang={fa?'de':'fa'} dir={fa?'ltr':'rtl'}><a href={localizedPath(locale,proverbPath(p))}>{fa?p.equivalent:p.proverb}</a></h2><p>{fa?proverbLearning[p.id].meaningFa:p.meaning}</p><a href={localizedPath(locale,proverbPath(p))}>{t.open}</a></li>)}</ul></>;}

export function LessonsPage({locale}:{locale:Locale}){const t=ui[locale];const fa=locale==='fa';return <><h1>{t.practiceTitle}</h1><p className="content-lead">{t.practiceLead}</p><LocalizedLessons locale={locale}/><aside className="content-panel no-print" id="lernpaket"><h2>{fa?'بستهٔ آموزشی پیشنهادی':'Geplantes Lernpaket'}</h2><p>{fa?'با ۵۰ ضرب‌المثل آلمانی در موقعیت‌های روزمره تمرین کنید. این بسته در حال آماده‌سازی است.':'50 persische Sprichwörter verstehen und im Alltag passend verwenden. Dieses Paket ist in Vorbereitung.'}</p><ul className="offer-list"><li>{fa?'۵۰ ضرب‌المثل با معنی و مثال روزمره':'50 Sprichwörter mit Bedeutung und Alltagsbeispiel'}</li><li>{fa?'تمرین و پاسخ برای مرور مستقل':'Übungen mit Lösungen zum selbstständigen Lernen'}</li><li>{fa?'کارت‌های یادگیری قابل چاپ':'Druckbare Lernkarten zur Wiederholung'}</li></ul><p className="offer-price">{fa?'قیمت پیشنهادی: ۹٫۹۰ یورو، پرداخت یک‌باره':'Geplanter Preis: 9,90 € einmalig'}</p><p className="offer-note">{fa?'این پیشنهاد برای بررسی علاقه است. هنوز امکان خرید یا پرداخت وجود ندارد.':'Wir prüfen derzeit das Interesse. Das Paket kann noch nicht gekauft oder bezahlt werden.'}</p></aside><InterestForm locale={locale}/><section className="no-print"><h2>{fa?'پرسش‌های رایج':'Häufige Fragen'}</h2><details><summary>{fa?'آیا مجموعه رایگان می‌ماند؟':'Bleibt die Sammlung kostenlos?'}</summary><p>{fa?'بله. مجموعه و تمرین رایگان بدون ثبت‌نام در دسترس هستند.':'Ja. Die Sammlung und die kostenlose Lernprobe bleiben ohne Anmeldung zugänglich.'}</p></details><details><summary>{fa?'چگونه تمرین را ذخیره کنم؟':'Wie speichere ich die Lernprobe?'}</summary><p>{fa?'دکمهٔ چاپ تمرین را بزنید و در پنجرهٔ چاپ مرورگر، ذخیره به صورت PDF را انتخاب کنید. پرسش‌ها و پاسخ‌ها در نسخهٔ چاپی قرار دارند.':'Wähle „Lernprobe drucken / als PDF speichern“ und anschließend im Druckdialog „Als PDF speichern“. Aufgaben und Lösungen werden mit ausgegeben.'}</p></details></section></>;}

export function AboutPage({locale}:{locale:Locale}){if(locale==='de')return <GermanAboutContent/>;return <><h1>راهنمای یادگیری با ضرب‌المثل</h1><p className="content-lead">این بخش برای فارسی‌زبان‌هایی است که می‌خواهند آلمانی یاد بگیرند. عبارت آلمانی را بخوانید و با کمک معنی فارسی و مثال روزمره، موقعیت استفاده از آن را بشناسید.</p><section><h2>چرا هر جمله به دو زبان تکرار نمی‌شود؟</h2><p>منوها، توضیح‌ها و پرسش‌ها به فارسی هستند. فقط متن‌هایی که برای یادگیری لازم‌اند، مانند خود ضرب‌المثل و مثال آلمانی، به آلمانی نمایش داده می‌شوند. برای یادگیری فارسی با توضیح آلمانی، زبان سایت را از بالای صفحه به Deutsch تغییر دهید.</p></section><section id="umschrift"><h2>چگونه تلفظ آلمانی را یاد بگیرم؟</h2><p>متن آلمانی با املای اصلی نمایش داده می‌شود. برای شنیدن تلفظ دقیق، از فایل صوتی یک فرهنگ معتبر آلمانی یا راهنمایی مدرس استفاده کنید. نوشتن تلفظ آلمانی با حروف فارسی نمی‌تواند همهٔ تفاوت‌های آوایی را دقیق نشان دهد.</p></section><section><h2>آیا معادل فارسی ترجمهٔ دقیق است؟</h2><p>نه همیشه. معادل فارسی مفهوم مشابهی دارد، اما ممکن است تصویر یا لحن متفاوتی داشته باشد. ابتدا معنی و مثال را بخوانید و سپس دو عبارت را مقایسه کنید.</p></section><section><h2>مثال‌ها و توضیح‌ها چگونه تهیه شده‌اند؟</h2><p>توضیح‌ها و مثال‌های روزمره با کمک هوش مصنوعی برای این مجموعه نوشته شده‌اند و نقل‌قول از منابع تاریخی نیستند. این سایت یک ابزار یادگیری است، نه یک مجموعهٔ پژوهشی. برای استناد علمی باید شکل دقیق هر عبارت را در منبع معتبر بررسی کنید.</p></section><section><h2>چگونه عبارت مورد نظر را پیدا کنم؟</h2><p>در مجموعه به آلمانی یا فارسی جست‌وجو کنید یا موضوعی را انتخاب کنید. زبان را از بالای صفحه تغییر دهید؛ همان ضرب‌المثل در نسخهٔ دیگر باز می‌ماند. انتخاب زبان در همین مرورگر ذخیره می‌شود.</p><a href="/fa">بازگشت به مجموعه</a></section><section><h2>چگونه تمرین کنم؟</h2><p>تمرین رایگان شامل پنج ضرب‌المثل آلمانی، مثال و پرسش با بازخورد فوری به فارسی است.</p><a href="/fa/lernpaket">شروع تمرین رایگان</a></section></>;}
