import type { Proverb } from '@/app/additional-proverbs';

export const moreProverbs: Proverb[] = [
  {
    id: 117,
    language: 'fa',
    proverb: 'آن را که حساب پاک است، از محاسبه چه باک است',
    equivalent: 'Ein gutes Gewissen ist ein sanftes Ruhekissen.',
    meaning: 'Wer ehrlich gehandelt hat, braucht eine Prüfung oder Abrechnung nicht zu fürchten.',
    category: 'Weisheit',
    note: 'Wörtlich: Wer eine saubere Rechnung hat, braucht die Abrechnung nicht zu fürchten.',
  },
  {
    id: 118,
    language: 'fa',
    proverb: 'آتش که گرفت، خشک و تر می‌سوزد',
    equivalent: 'Wenn es brennt, trifft es Schuldige wie Unschuldige.',
    meaning: 'Eine große Krise unterscheidet oft nicht zwischen Beteiligten und Unbeteiligten.',
    category: 'Alltag',
    note: 'Wörtlich: Wenn das Feuer ausbricht, verbrennt es Trockenes und Feuchtes.',
  },
  {
    id: 119,
    language: 'fa',
    proverb: 'آش نخورده و دهن سوخته',
    equivalent: 'Unschuldig in Verdacht geraten.',
    meaning: 'Jemand muss die Folgen tragen oder wird beschuldigt, obwohl er nichts getan hat.',
    category: 'Alltag',
    note: 'Wörtlich: Keine Suppe gegessen und doch den Mund verbrannt.',
  },
  {
    id: 120,
    language: 'fa',
    proverb: 'بزک نمیر، بهار می‌آد، خربزه با خیار می‌آد',
    equivalent: 'Auf den Sankt-Nimmerleins-Tag vertrösten.',
    meaning: 'Ein Versprechen hilft wenig, wenn seine Erfüllung ungewiss oder viel zu spät ist.',
    category: 'Geduld',
    note: 'Wörtlich: Zicklein, stirb nicht; der Frühling kommt und bringt Melonen und Gurken.',
  },
  {
    id: 121,
    language: 'fa',
    proverb: 'پیشگیری بهتر از درمان است',
    equivalent: 'Vorbeugen ist besser als heilen.',
    meaning: 'Es ist klüger, ein Problem zu verhindern, als später seine Folgen zu beseitigen.',
    category: 'Weisheit',
    note: 'Die wörtliche Bedeutung entspricht genau dem deutschen Sprichwort.',
  },
  {
    id: 122,
    language: 'fa',
    proverb: 'تا مرد سخن نگفته باشد، عیب و هنرش نهفته باشد',
    equivalent: 'An der Sprache erkennt man den Menschen.',
    meaning: 'Erst durch seine Worte zeigt ein Mensch seine Fähigkeiten und Schwächen.',
    category: 'Weisheit',
    note: 'Wörtlich: Solange ein Mensch nicht gesprochen hat, bleiben Fehler und Können verborgen.',
  },
  {
    id: 123,
    language: 'fa',
    proverb: 'چوب را که برداری، گربهٔ دزده فرار می‌کند',
    equivalent: 'Getroffene Hunde bellen.',
    meaning: 'Wer sich schuldig fühlt, verrät sich oft durch eine auffällige Reaktion.',
    category: 'Alltag',
    note: 'Wörtlich: Hebt man den Stock, läuft die diebische Katze davon.',
  },
  {
    id: 124,
    language: 'fa',
    proverb: 'دود از کنده بلند می‌شود',
    equivalent: 'In den Alten steckt noch Kraft.',
    meaning: 'Erfahrung und Tatkraft älterer Menschen sollte man nicht unterschätzen.',
    category: 'Weisheit',
    note: 'Wörtlich: Der Rauch steigt aus dem alten Holzklotz auf.',
  },
  {
    id: 125,
    language: 'fa',
    proverb: 'دیر و زود دارد، سوخت و سوز ندارد',
    equivalent: 'Was lange währt, wird endlich gut.',
    meaning: 'Etwas kann sich verzögern, wird aber am Ende dennoch sicher eintreten.',
    category: 'Geduld',
    note: 'Wörtlich: Es gibt ein Früher oder Später, aber kein Ausbleiben.',
  },
  {
    id: 126,
    language: 'fa',
    proverb: 'سال به سال، دریغ از پارسال',
    equivalent: 'Früher war alles besser.',
    meaning: 'Die Lage verschlechtert sich so, dass man jedes Jahr dem vergangenen nachtrauert.',
    category: 'Alltag',
    note: 'Wörtlich: Von Jahr zu Jahr sehnt man sich nach dem Vorjahr.',
  },
  {
    id: 127,
    language: 'fa',
    proverb: 'سری که درد نمی‌کند، دستمال نمی‌بندند',
    equivalent: 'Schlafende Hunde soll man nicht wecken.',
    meaning: 'Man sollte sich ohne Not keine zusätzlichen Probleme schaffen.',
    category: 'Weisheit',
    note: 'Wörtlich: Um einen Kopf, der nicht schmerzt, bindet man kein Tuch.',
  },
  {
    id: 128,
    language: 'fa',
    proverb: 'شنیدن کی بود مانند دیدن',
    equivalent: 'Sehen heißt glauben.',
    meaning: 'Eigene Anschauung überzeugt stärker als eine bloße Erzählung.',
    category: 'Weisheit',
    note: 'Wörtlich: Wann wäre Hören je wie Sehen gewesen?',
  },
  {
    id: 129,
    language: 'fa',
    proverb: 'صبر تلخ است، ولیکن برِ شیرین دارد',
    equivalent: 'Geduld ist bitter, aber ihre Frucht ist süß.',
    meaning: 'Ausdauer kann schwerfallen, führt jedoch häufig zu einem guten Ergebnis.',
    category: 'Geduld',
    note: 'Die deutsche Entsprechung folgt dem Bild des persischen Sprichworts.',
  },
  {
    id: 130,
    language: 'fa',
    proverb: 'غوره نشده، مویز شده',
    equivalent: 'Das Küken will klüger sein als die Henne.',
    meaning: 'Jemand hält sich voreilig für erfahren, obwohl ihm wichtige Entwicklungsschritte fehlen.',
    category: 'Weisheit',
    note: 'Wörtlich: Noch keine unreife Traube geworden, aber schon eine Rosine.',
  },
  {
    id: 131,
    language: 'fa',
    proverb: 'کل اگر طبیب بودی، سر خود دوا نمودی',
    equivalent: 'Arzt, heile dich selbst.',
    meaning: 'Wer andere beraten will, sollte zunächst seine eigenen Probleme lösen können.',
    category: 'Weisheit',
    note: 'Wörtlich: Wäre der Kahle ein Arzt, hätte er seinen eigenen Kopf geheilt.',
  },
  {
    id: 132,
    language: 'fa',
    proverb: 'کوه به کوه نمی‌رسد، آدم به آدم می‌رسد',
    equivalent: 'Man sieht sich immer zweimal im Leben.',
    meaning: 'Menschen können sich unerwartet wiederbegegnen und sollten fair miteinander umgehen.',
    category: 'Alltag',
    note: 'Wörtlich: Berg trifft nicht auf Berg, aber Mensch trifft auf Mensch.',
  },
  {
    id: 133,
    language: 'fa',
    proverb: 'مهمان حبیب خداست',
    equivalent: 'Gäste sind ein Segen.',
    meaning: 'Gäste verdienen einen herzlichen Empfang und großzügige Gastfreundschaft.',
    category: 'Zusammenarbeit',
    note: 'Wörtlich: Der Gast ist der Liebling Gottes.',
  },
  {
    id: 134,
    language: 'fa',
    proverb: 'نه سیخ بسوزد، نه کباب',
    equivalent: 'Einen goldenen Mittelweg finden.',
    meaning: 'Eine Lösung soll beide Seiten schonen und unnötigen Schaden vermeiden.',
    category: 'Zusammenarbeit',
    note: 'Wörtlich: Weder soll der Spieß verbrennen noch der Kebab.',
  },
  {
    id: 135,
    language: 'fa',
    proverb: 'هر سخن جایی و هر نکته مکانی دارد',
    equivalent: 'Alles zu seiner Zeit und an seinem Ort.',
    meaning: 'Auch richtige Worte müssen zur passenden Gelegenheit ausgesprochen werden.',
    category: 'Weisheit',
    note: 'Wörtlich: Jedes Wort hat seinen Ort und jeder Gedanke seinen Platz.',
  },
  {
    id: 136,
    language: 'fa',
    proverb: 'یک بام و دو هوا',
    equivalent: 'Mit zweierlei Maß messen.',
    meaning: 'Gleiche Fälle werden aus Eigennutz nach unterschiedlichen Regeln beurteilt.',
    category: 'Alltag',
    note: 'Wörtlich: Ein Dach und zwei verschiedene Wetterlagen.',
  },
  {
    id: 137,
    language: 'fa',
    proverb: 'آدم گرسنه سنگ را هم می‌خورد',
    equivalent: 'Hunger ist der beste Koch.',
    meaning: 'Großer Hunger macht selbst einfache oder wenig verlockende Nahrung begehrenswert.',
    category: 'Alltag',
    note: 'Wörtlich: Ein hungriger Mensch isst sogar Steine.',
  },
  {
    id: 138,
    language: 'fa',
    proverb: 'آب که یک جا بماند، می‌گندد',
    equivalent: 'Wer rastet, der rostet.',
    meaning: 'Ohne Bewegung, Lernen und Veränderung verliert man Fähigkeiten und Lebendigkeit.',
    category: 'Arbeit',
    note: 'Wörtlich: Wasser, das an einer Stelle bleibt, wird faul.',
  },
  {
    id: 139,
    language: 'fa',
    proverb: 'پایان شب سیه سپید است',
    equivalent: 'Nach Regen folgt Sonnenschein.',
    meaning: 'Auch eine schwere Zeit geht vorüber und macht besseren Tagen Platz.',
    category: 'Geduld',
    note: 'Wörtlich: Am Ende der schwarzen Nacht wird es hell.',
  },
  {
    id: 140,
    language: 'fa',
    proverb: 'به عمل کار برآید، به سخندانی نیست',
    equivalent: 'Taten sagen mehr als Worte.',
    meaning: 'Ergebnisse entstehen durch Handeln und nicht allein durch schöne Reden.',
    category: 'Arbeit',
    note: 'Wörtlich: Durch Handeln gelingt die Sache, nicht durch Beredsamkeit.',
  },
  {
    id: 141,
    language: 'fa',
    proverb: 'تا سه نشود، بازی نشود',
    equivalent: 'Aller guten Dinge sind drei.',
    meaning: 'Oft braucht es einen dritten Versuch oder ein drittes Ereignis, bis etwas vollständig wird.',
    category: 'Alltag',
    note: 'Wörtlich: Solange es nicht drei wird, beginnt das Spiel nicht.',
  },
  {
    id: 142,
    language: 'fa',
    proverb: 'خروس بی‌محل',
    equivalent: 'Alles zu seiner Zeit.',
    meaning: 'So nennt man jemanden, der unpassend oder zum falschen Zeitpunkt spricht und handelt.',
    category: 'Alltag',
    note: 'Wörtlich: Ein Hahn, der zur unpassenden Zeit kräht.',
  },
  {
    id: 143,
    language: 'fa',
    proverb: 'درخت هرچه پربارتر، افتاده‌تر',
    equivalent: 'Wahre Größe ist bescheiden.',
    meaning: 'Je mehr Können und Wert ein Mensch besitzt, desto bescheidener sollte er auftreten.',
    category: 'Weisheit',
    note: 'Wörtlich: Je voller ein Baum Früchte trägt, desto tiefer neigt er sich.',
  },
  {
    id: 144,
    language: 'fa',
    proverb: 'دست که نمک ندارد',
    equivalent: 'Undank ist der Welt Lohn.',
    meaning: 'Güte und Hilfe werden von manchen Menschen leider nicht gewürdigt oder erwidert.',
    category: 'Alltag',
    note: 'Wörtlich: Eine Hand, die kein Salz hat; Salz steht hier für Dankbarkeit und Treue.',
  },
  {
    id: 145,
    language: 'fa',
    proverb: 'دو صد گفته چون نیم کردار نیست',
    equivalent: 'Taten sagen mehr als Worte.',
    meaning: 'Selbst viele Versprechen sind weniger wert als eine einzige konkrete Handlung.',
    category: 'Arbeit',
    note: 'Wörtlich: Zweihundert Worte sind nicht so viel wie eine halbe Tat.',
  },
  {
    id: 146,
    language: 'fa',
    proverb: 'رنگ رخساره خبر می‌دهد از سر ضمیر',
    equivalent: 'Das Gesicht ist der Spiegel der Seele.',
    meaning: 'Gefühle und innere Gedanken zeigen sich häufig im Gesicht eines Menschen.',
    category: 'Weisheit',
    note: 'Wörtlich: Die Gesichtsfarbe berichtet vom verborgenen Inneren.',
  },
  {
    id: 147,
    language: 'fa',
    proverb: 'زبان خوش، مار را از سوراخ بیرون می‌آورد',
    equivalent: 'Mit Freundlichkeit kommt man weiter.',
    meaning: 'Höfliche und freundliche Worte können selbst schwierige Menschen überzeugen.',
    category: 'Zusammenarbeit',
    note: 'Wörtlich: Eine freundliche Zunge holt die Schlange aus ihrem Loch.',
  },
  {
    id: 148,
    language: 'fa',
    proverb: 'کاسهٔ داغ‌تر از آش',
    equivalent: 'Päpstlicher sein als der Papst.',
    meaning: 'Jemand vertritt eine Sache übereifriger als die eigentlich betroffene Person.',
    category: 'Alltag',
    note: 'Wörtlich: Die Schüssel ist heißer als die Suppe.',
  },
  {
    id: 149,
    language: 'fa',
    proverb: 'کسی که خواب است را می‌شود بیدار کرد، اما کسی که خودش را به خواب زده نه',
    equivalent: 'Wer nicht verstehen will, dem ist nicht zu helfen.',
    meaning: 'Unwissen lässt sich beheben, absichtliche Verweigerung dagegen kaum.',
    category: 'Weisheit',
    note: 'Wörtlich: Einen Schlafenden kann man wecken, einen, der sich schlafend stellt, nicht.',
  },
  {
    id: 150,
    language: 'fa',
    proverb: 'مشت نمونهٔ خروار است',
    equivalent: 'An der Probe erkennt man das Ganze.',
    meaning: 'Eine kleine, typische Stichprobe kann viel über die Qualität des Ganzen verraten.',
    category: 'Weisheit',
    note: 'Wörtlich: Eine Handvoll ist das Muster eines großen Gewichtsmaßes.',
  },
  {
    id: 151,
    language: 'fa',
    proverb: 'هرچه بگندد نمکش می‌زنند، وای به روزی که بگندد نمک',
    equivalent: 'Der Fisch stinkt vom Kopf her.',
    meaning: 'Wenn ausgerechnet die Verantwortlichen oder Kontrollierenden versagen, wird es besonders schlimm.',
    category: 'Weisheit',
    note: 'Wörtlich: Verdorbenes salzt man; wehe aber dem Tag, an dem das Salz selbst verdirbt.',
  },
  {
    id: 152,
    language: 'fa',
    proverb: 'یک نه بگو و نه ماه آسوده باش',
    equivalent: 'Ein klares Nein erspart langen Ärger.',
    meaning: 'Eine rechtzeitige Absage ist besser als monatelange Belastung durch eine falsche Zusage.',
    category: 'Weisheit',
    note: 'Wörtlich: Sag einmal Nein und sei neun Monate lang unbesorgt.',
  },
  {
    id: 153,
    language: 'fa',
    proverb: 'جلوی استاد معلق‌بازی',
    equivalent: 'Den Meister will der Lehrling belehren.',
    meaning: 'Jemand versucht, vor einem erfahrenen Fachmenschen mit dessen eigenem Können anzugeben.',
    category: 'Arbeit',
    note: 'Wörtlich: Vor dem Meister Kunststücke vorführen.',
  },
  {
    id: 154,
    language: 'fa',
    proverb: 'با حلوا حلوا گفتن، دهان شیرین نمی‌شود',
    equivalent: 'Von Worten allein wird niemand satt.',
    meaning: 'Bloßes Reden und Wünschen ersetzt keine konkrete Tat und schafft kein Ergebnis.',
    category: 'Arbeit',
    note: 'Wörtlich: Vom wiederholten Wort Halwa wird der Mund nicht süß.',
  },
  {
    id: 155,
    language: 'fa',
    proverb: 'تا یار که را خواهد و میلش به که باشد',
    equivalent: 'Die Wahl liegt bei dem, der sich entscheiden muss.',
    meaning: 'Am Ende entscheidet die Zuneigung oder Gunst der Person, um die geworben wird.',
    category: 'Alltag',
    note: 'Wörtlich: Es bleibt abzuwarten, wen die geliebte Person will und wem sie zugeneigt ist.',
  },
  {
    id: 156,
    language: 'fa',
    proverb: 'هر که را بهر کاری ساختند',
    equivalent: 'Schuster, bleib bei deinem Leisten.',
    meaning: 'Jeder Mensch hat besondere Fähigkeiten und sollte Aufgaben passend zu ihnen übernehmen.',
    category: 'Arbeit',
    note: 'Wörtlich: Jeden hat man für eine bestimmte Arbeit geschaffen.',
  },
  {
    id: 157,
    language: 'fa',
    proverb: 'هر آمدنی، رفتنی دارد',
    equivalent: 'Alles hat ein Ende.',
    meaning: 'Nichts im Leben bleibt für immer; auf jede Ankunft folgt irgendwann ein Abschied.',
    category: 'Weisheit',
    note: 'Wörtlich: Jedes Kommen hat auch ein Gehen.',
  },
  {
    id: 158,
    language: 'fa',
    proverb: 'دو پادشاه در یک اقلیم نگنجند',
    equivalent: 'Zwei Hähne vertragen sich nicht auf einem Mist.',
    meaning: 'Zwei Menschen mit gleichem Machtanspruch geraten in einem Bereich leicht aneinander.',
    category: 'Zusammenarbeit',
    note: 'Wörtlich: Zwei Könige finden in einem Reich keinen Platz.',
  },
  {
    id: 159,
    language: 'de',
    proverb: 'Alte Liebe rostet nicht.',
    equivalent: 'عشق قدیمی از دل نمی‌رود',
    meaning: 'احساس عمیق و قدیمی ممکن است با گذشت زمان هم از بین نرود.',
    category: 'خانواده',
    note: 'ترجمهٔ لفظی: عشق قدیمی زنگ نمی‌زند.',
  },
  {
    id: 160,
    language: 'de',
    proverb: 'Alter schützt vor Torheit nicht.',
    equivalent: 'پیری مانع نادانی نیست',
    meaning: 'بالا رفتن سن به‌تنهایی تضمین نمی‌کند که انسان همیشه عاقلانه رفتار کند.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: سن بالا از حماقت محافظت نمی‌کند.',
  },
  {
    id: 161,
    language: 'de',
    proverb: 'Andere Mütter haben auch schöne Töchter.',
    equivalent: 'قحطی آدم نیست',
    meaning: 'اگر یک رابطه یا فرصت از دست برود، گزینه‌های خوب دیگری هم وجود دارند.',
    category: 'خانواده',
    note: 'ترجمهٔ لفظی: مادرهای دیگر هم دختران زیبایی دارند.',
  },
  {
    id: 162,
    language: 'de',
    proverb: 'Aufgeschoben ist nicht aufgehoben.',
    equivalent: 'کارِ عقب‌افتاده، از میان نرفته است',
    meaning: 'به تعویق انداختن یک کار به معنای لغو شدن یا فراموش شدن آن نیست.',
    category: 'کار',
    note: 'ترجمهٔ لفظی: به‌تعویق‌افتاده، لغوشده نیست.',
  },
  {
    id: 163,
    language: 'de',
    proverb: 'Aus Schaden wird man klug.',
    equivalent: 'مارگزیده از ریسمان سیاه و سفید می‌ترسد',
    meaning: 'انسان از تجربه‌های تلخ درس می‌گیرد و در آینده محتاط‌تر می‌شود.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: انسان از زیان عاقل می‌شود.',
  },
  {
    id: 164,
    language: 'de',
    proverb: 'Besser allein als in schlechter Gesellschaft.',
    equivalent: 'تنهایی بهتر از همنشین بد است',
    meaning: 'تنها ماندن بهتر از معاشرتی است که به انسان آسیب می‌زند.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی و مفهوم معادل فارسی بسیار نزدیک‌اند.',
  },
  {
    id: 165,
    language: 'de',
    proverb: 'Besser zweimal fragen als einmal irren.',
    equivalent: 'پرسیدن عیب نیست، ندانستن عیب است',
    meaning: 'سؤال دوباره بهتر از تصمیم اشتباهی است که از ناآگاهی گرفته شود.',
    category: 'کار',
    note: 'ترجمهٔ لفظی: دو بار پرسیدن بهتر از یک بار اشتباه کردن است.',
  },
  {
    id: 166,
    language: 'de',
    proverb: 'Da liegt der Hund begraben.',
    equivalent: 'اصل مطلب همین‌جاست',
    meaning: 'این عبارت به علت اصلی یا نکتهٔ پنهان و تعیین‌کنندهٔ یک موضوع اشاره دارد.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: سگ آنجا دفن شده است.',
  },
  {
    id: 167,
    language: 'de',
    proverb: 'Das Auge isst mit.',
    equivalent: 'اول چشم می‌خورد، بعد دهان',
    meaning: 'ظاهر و شیوهٔ ارائهٔ غذا بر لذت و اشتهای انسان اثر می‌گذارد.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: چشم هم همراه انسان غذا می‌خورد.',
  },
  {
    id: 168,
    language: 'de',
    proverb: 'Das Glück ist mit den Tüchtigen.',
    equivalent: 'از تو حرکت، از خدا برکت',
    meaning: 'شانس بیشتر به کسی کمک می‌کند که خودش تلاش و اقدام می‌کند.',
    category: 'اراده',
    note: 'ترجمهٔ لفظی: بخت با افراد کوشا همراه است.',
  },
  {
    id: 169,
    language: 'de',
    proverb: 'Der Fisch stinkt vom Kopf her.',
    equivalent: 'هرچه بگندد نمکش می‌زنند، وای به روزی که بگندد نمک',
    meaning: 'فساد یا نابسامانی یک مجموعه اغلب از مدیریت و رأس آن آغاز می‌شود.',
    category: 'کار',
    note: 'ترجمهٔ لفظی: ماهی از سرش بو می‌گیرد.',
  },
  {
    id: 170,
    language: 'de',
    proverb: 'Die Hoffnung stirbt zuletzt.',
    equivalent: 'انسان به امید زنده است',
    meaning: 'حتی در دشوارترین شرایط، امید معمولاً آخرین چیزی است که از دست می‌رود.',
    category: 'اراده',
    note: 'ترجمهٔ لفظی: امید آخر از همه می‌میرد.',
  },
  {
    id: 171,
    language: 'de',
    proverb: 'Die Zeit vergeht wie im Flug.',
    equivalent: 'عمر چون برق می‌گذرد',
    meaning: 'زمان، به‌ویژه هنگام سرگرمی یا مشغله، بسیار سریع سپری می‌شود.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: زمان گویی در پرواز می‌گذرد.',
  },
  {
    id: 172,
    language: 'de',
    proverb: 'Eigenlob stinkt.',
    equivalent: 'مشک آن است که خود ببوید، نه آنکه عطار بگوید',
    meaning: 'ارزش واقعی نیازی به خودستایی ندارد و باید برای دیگران آشکار باشد.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: تعریف کردن از خود بوی بد می‌دهد.',
  },
  {
    id: 173,
    language: 'de',
    proverb: 'Ein Bild sagt mehr als tausend Worte.',
    equivalent: 'شنیدن کی بود مانند دیدن',
    meaning: 'یک تصویر می‌تواند مطلبی را روشن‌تر و سریع‌تر از توضیح طولانی منتقل کند.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: یک تصویر بیش از هزار واژه حرف می‌زند.',
  },
  {
    id: 174,
    language: 'de',
    proverb: 'Ein blindes Huhn findet auch mal ein Korn.',
    equivalent: 'گاهی شانس به نادان هم رو می‌کند',
    meaning: 'حتی فرد کم‌تجربه یا ناموفق هم ممکن است گاهی به‌طور اتفاقی موفق شود.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: مرغ کور هم گاهی دانه‌ای پیدا می‌کند.',
  },
  {
    id: 175,
    language: 'de',
    proverb: 'Ein gutes Gewissen ist ein sanftes Ruhekissen.',
    equivalent: 'آن را که حساب پاک است، از محاسبه چه باک است',
    meaning: 'کسی که درستکار بوده است، با آرامش زندگی می‌کند و از بررسی نمی‌ترسد.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: وجدان آسوده، بالش نرم خواب است.',
  },
  {
    id: 176,
    language: 'de',
    proverb: 'Einmal ist keinmal.',
    equivalent: 'یک بار به حساب نمی‌آید',
    meaning: 'یک اتفاق یا یک بار امتحان کردن برای قضاوت یا ایجاد عادت کافی نیست.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: یک بار، هیچ بار است.',
  },
  {
    id: 177,
    language: 'de',
    proverb: 'Erst denken, dann handeln.',
    equivalent: 'اول فکر، بعد عمل',
    meaning: 'پیش از اقدام باید پیامدها را سنجید و تصمیم را با دقت گرفت.',
    category: 'کار',
    note: 'ترجمهٔ لفظی و مفهوم فارسی یکسان‌اند.',
  },
  {
    id: 178,
    language: 'de',
    proverb: 'Es ist noch kein Meister vom Himmel gefallen.',
    equivalent: 'هیچ‌کس استاد به دنیا نمی‌آید',
    meaning: 'مهارت بدون یادگیری، تمرین و پذیرفتن اشتباه‌ها به دست نمی‌آید.',
    category: 'کار',
    note: 'ترجمهٔ لفظی: هنوز هیچ استادی از آسمان نیفتاده است.',
  },
  {
    id: 179,
    language: 'de',
    proverb: 'Es wird nichts so heiß gegessen, wie es gekocht wird.',
    equivalent: 'هیچ آشی به داغی دیگش خورده نمی‌شود',
    meaning: 'مشکلات یا تهدیدها هنگام اجرا معمولاً از آنچه ابتدا به نظر می‌رسند ملایم‌ترند.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: هیچ‌چیز به داغی زمانی که پخته می‌شود، خورده نمی‌شود.',
  },
  {
    id: 180,
    language: 'de',
    proverb: 'Freunde erkennt man in der Not.',
    equivalent: 'دوست آن باشد که گیرد دست دوست در پریشان‌حالی و درماندگی',
    meaning: 'دوستی واقعی زمانی آشکار می‌شود که انسان گرفتار و نیازمند کمک است.',
    category: 'خانواده',
    note: 'ترجمهٔ لفظی: دوستان را در هنگام نیاز می‌شناسند.',
  },
  {
    id: 181,
    language: 'de',
    proverb: 'Früh übt sich, was ein Meister werden will.',
    equivalent: 'کار نیکو کردن از پُر کردن است',
    meaning: 'کسی که می‌خواهد در کاری استاد شود، باید از زودهنگام و بسیار تمرین کند.',
    category: 'کار',
    note: 'ترجمهٔ لفظی: آن‌که می‌خواهد استاد شود، از کودکی تمرین می‌کند.',
  },
  {
    id: 182,
    language: 'de',
    proverb: 'Getroffene Hunde bellen.',
    equivalent: 'چوب را که برداری، گربهٔ دزده فرار می‌کند',
    meaning: 'واکنش تند یک نفر گاهی نشان می‌دهد که انتقاد به نقطهٔ حساس یا واقعی زده است.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: سگ‌هایی که هدف قرار گرفته‌اند، پارس می‌کنند.',
  },
  {
    id: 183,
    language: 'de',
    proverb: 'Guter Rat ist teuer.',
    equivalent: 'در کار گره‌خورده، تدبیر کمیاب است',
    meaning: 'در موقعیت دشوار، پیدا کردن راه‌حل درست آسان نیست و ارزش زیادی دارد.',
    category: 'کار',
    note: 'ترجمهٔ لفظی: راهنمایی خوب گران است.',
  },
  {
    id: 184,
    language: 'de',
    proverb: 'Handwerk hat goldenen Boden.',
    equivalent: 'هنر نان‌آور است',
    meaning: 'داشتن یک مهارت عملی و حرفه‌ای می‌تواند پایهٔ درآمد و امنیت زندگی باشد.',
    category: 'کار',
    note: 'ترجمهٔ لفظی: حرفه و صنعت، زمینی از طلا دارد.',
  },
  {
    id: 185,
    language: 'de',
    proverb: 'In der Kürze liegt die Würze.',
    equivalent: 'کم گوی و گزیده گوی چون دُر',
    meaning: 'سخن کوتاه و دقیق معمولاً اثرگذارتر از توضیح طولانی و پراکنده است.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: مزه و جذابیت در کوتاهی است.',
  },
  {
    id: 186,
    language: 'de',
    proverb: 'Jeder ist sich selbst der Nächste.',
    equivalent: 'چراغی که به خانه رواست، به مسجد حرام است',
    meaning: 'انسان معمولاً نخست به نیازهای خود و نزدیکانش توجه می‌کند.',
    category: 'خانواده',
    note: 'ترجمهٔ لفظی: هرکس نزدیک‌ترین فرد به خودش است.',
  },
  {
    id: 187,
    language: 'de',
    proverb: 'Kleine Geschenke erhalten die Freundschaft.',
    equivalent: 'هدیه، دوستی را تازه نگه می‌دارد',
    meaning: 'نشانه‌های کوچک توجه و محبت می‌توانند رابطه و دوستی را تقویت کنند.',
    category: 'خانواده',
    note: 'ترجمهٔ لفظی: هدیه‌های کوچک دوستی را حفظ می‌کنند.',
  },
  {
    id: 188,
    language: 'de',
    proverb: 'Man lernt nie aus.',
    equivalent: 'ز گهواره تا گور دانش بجوی',
    meaning: 'یادگیری در هیچ سنی پایان نمی‌یابد و همیشه چیز تازه‌ای برای آموختن هست.',
    category: 'کار',
    note: 'ترجمهٔ لفظی: انسان هرگز یادگیری را تمام نمی‌کند.',
  },
  {
    id: 189,
    language: 'de',
    proverb: 'Man soll die Feste feiern, wie sie fallen.',
    equivalent: 'فرصت را باید غنیمت شمرد',
    meaning: 'باید از موقعیت‌های خوب و شادی‌های زندگی در همان زمان مناسب بهره برد.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: جشن‌ها را باید همان‌گونه که پیش می‌آیند برگزار کرد.',
  },
  {
    id: 190,
    language: 'de',
    proverb: 'Mit Speck fängt man Mäuse.',
    equivalent: 'طمع، دام آدم است',
    meaning: 'با پیشنهاد جذاب می‌توان کسی را وسوسه کرد و به دام انداخت.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: موش را با تکهٔ گوشت چرب می‌گیرند.',
  },
  {
    id: 191,
    language: 'de',
    proverb: 'Neue Besen kehren gut.',
    equivalent: 'جاروی نو خوب جارو می‌کند',
    meaning: 'فرد یا روش تازه در آغاز معمولاً با انگیزهٔ زیاد و نتیجهٔ خوب ظاهر می‌شود.',
    category: 'کار',
    note: 'ترجمهٔ لفظی و معادل فارسی یکسان‌اند.',
  },
  {
    id: 192,
    language: 'de',
    proverb: 'Papier ist geduldig.',
    equivalent: 'روی کاغذ همه‌چیز آسان است',
    meaning: 'می‌توان هر ادعا یا برنامه‌ای را نوشت، اما واقعیت لزوماً آن را تأیید نمی‌کند.',
    category: 'کار',
    note: 'ترجمهٔ لفظی: کاغذ صبور است.',
  },
  {
    id: 193,
    language: 'de',
    proverb: 'Selbst ist der Mann.',
    equivalent: 'کس نخارد پشت من، جز ناخن انگشت من',
    meaning: 'بهتر است انسان برای حل مشکل خود دست‌به‌کار شود و تنها منتظر دیگران نماند.',
    category: 'اراده',
    note: 'ترجمهٔ لفظی: خودِ آدم باید کار را انجام دهد.',
  },
  {
    id: 194,
    language: 'de',
    proverb: 'Vertrauen ist gut, Kontrolle ist besser.',
    equivalent: 'اعتماد خوب است، حساب‌رسی بهتر',
    meaning: 'اعتماد ارزشمند است، اما در امور مهم بررسی و اطمینان نیز لازم است.',
    category: 'کار',
    note: 'ترجمهٔ لفظی و مفهوم معادل فارسی بسیار نزدیک‌اند.',
  },
  {
    id: 195,
    language: 'de',
    proverb: 'Wer den Pfennig nicht ehrt, ist des Talers nicht wert.',
    equivalent: 'قطره قطره جمع گردد، وانگهی دریا شود',
    meaning: 'کسی که قدر مقدارهای کوچک را نداند، شایستهٔ دارایی بزرگ هم نیست.',
    category: 'کار',
    note: 'ترجمهٔ لفظی: کسی که سکهٔ کوچک را ارج ننهد، ارزش سکهٔ بزرگ را ندارد.',
  },
  {
    id: 196,
    language: 'de',
    proverb: 'Wer rastet, der rostet.',
    equivalent: 'آب که یک جا بماند، می‌گندد',
    meaning: 'بی‌تحرکی و تمرین نکردن باعث می‌شود توانایی‌های انسان کاهش یابد.',
    category: 'اراده',
    note: 'ترجمهٔ لفظی: کسی که از حرکت بازبماند، زنگ می‌زند.',
  },
  {
    id: 197,
    language: 'de',
    proverb: 'Wer schweigt, stimmt zu.',
    equivalent: 'سکوت علامت رضاست',
    meaning: 'اگر کسی مخالفت خود را بیان نکند، سکوت او ممکن است نشانهٔ موافقت دانسته شود.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: کسی که سکوت می‌کند، موافق است.',
  },
  {
    id: 198,
    language: 'de',
    proverb: 'Wo Licht ist, ist auch Schatten.',
    equivalent: 'هر خوبی، عیبی هم دارد',
    meaning: 'تقریباً هر وضعیت مثبت در کنار مزایای خود، جنبه‌های منفی هم دارد.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: هرجا نور هست، سایه هم هست.',
  },
  {
    id: 199,
    language: 'de',
    proverb: 'Jeder kehre vor seiner eigenen Tür.',
    equivalent: 'یک سوزن به خودت بزن، یک جوالدوز به مردم',
    meaning: 'انسان باید پیش از انتقاد از دیگران، خطاها و مسئولیت‌های خودش را بررسی کند.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی: هرکس جلوی درِ خانهٔ خودش را جارو کند.',
  },
  {
    id: 200,
    language: 'de',
    proverb: 'Was du nicht willst, das man dir tu, das füg auch keinem andern zu.',
    equivalent: 'آنچه برای خود نمی‌پسندی، برای دیگران مپسند',
    meaning: 'با دیگران همان‌گونه رفتار کن که انتظار داری آنان با تو رفتار کنند.',
    category: 'رفتار',
    note: 'ترجمهٔ لفظی و مفهوم فارسی هر دو همان قاعدهٔ طلایی اخلاق را بیان می‌کنند.',
  },
];
