import type { Metadata } from 'next';
import ContentShell from '@/components/content-shell';
export const metadata:Metadata={title:'Über die Sammlung: Übersetzung, Umschrift und Beispiele | Zarbol Masal',description:'So nutzt du Zarbol Masal: persischer Originaltext, vereinfachte Umschrift, deutsche Entsprechung und Alltagsbeispiele. Hinweise zu Übersetzung und Herkunft.',alternates:{canonical:'/ueber-die-sammlung'},openGraph:{title:'So funktioniert Zarbol Masal',description:'Übersetzung, Umschrift und Beispiele verständlich erklärt.',url:'/ueber-die-sammlung'}};
export default function About(){return <ContentShell>
  <nav className="content-breadcrumbs" aria-label="Brotkrumennavigation"><a href="/">Sprichwörter</a><span> / Über die Sammlung</span></nav>
  <h1>Persische Sprichwörter auf Deutsch verstehen</h1>
  <p className="content-lead">Zarbol Masal ist eine zweisprachige Lernsammlung. Sie verbindet persische Sprichwörter mit deutschen Entsprechungen, verständlichen Erklärungen und Beispielen – auch für Menschen, die keine persische Schrift lesen können.</p>
  <p lang="fa" dir="rtl">ضرب‌المثل یک مجموعهٔ آموزشی دوزبانه است. متن فارسی، آوانویسی لاتین، معادل آلمانی، معنی و مثال‌های روزمره به یادگیری کمک می‌کنند.</p>
  <section><h2>Ist die deutsche Entsprechung eine genaue Übersetzung?</h2><p>Nicht immer. Die deutsche Entsprechung stellt eine ähnliche Aussage gegenüber. Die wörtliche Übersetzung erklärt dagegen das Bild des persischen Originals. Beides wird getrennt dargestellt, weil Bedeutung und Ton nicht in jedem Zusammenhang deckungsgleich sind.</p><p>Zum Beispiel steht „Kleinvieh macht auch Mist“ neben einem persischen Sprichwort über Tropfen, die ein Meer bilden. Die Bilder unterscheiden sich; gemeinsam ist ihnen die Idee, dass viele kleine Beiträge zusammen viel bewirken.</p><a href="/sprichwoerter/1-kleinvieh-macht-auch-mist">Dieses Beispiel mit Erklärung lesen</a></section>
  <section id="umschrift"><h2>Wie liest man die lateinische Umschrift?</h2><p>Die Umschrift ist eine vereinfachte Lesehilfe und keine vollständige Lautschrift. Sie erleichtert den Einstieg in persische Wörter. Aussprache und Schreibweisen können je nach Region und Sprecher variieren.</p><dl className="pronunciation-list"><dt>â</dt><dd>Ein langes a.</dd><dt>sh</dt><dd>Wie sch im deutschen Wort „Schule“.</dd><dt>ch</dt><dd>Wie tsch in „Tschüss“.</dd><dt>kh</dt><dd>Ein rauer ch-Laut, ungefähr wie in „Bach“.</dd><dt>zh</dt><dd>Ein stimmhafter sch-Laut, ungefähr wie in „Journal“.</dd><dt>gh / q</dt><dd>Laute im hinteren Mund- oder Rachenraum, für die es im Deutschen keine genaue Entsprechung gibt.</dd></dl><p lang="fa" dir="rtl">آوانویسی لاتین فقط یک راهنمای ساده برای خواندن است و جای شنیدن تلفظ از گویشور فارسی‌زبان را نمی‌گیرد.</p></section>
  <section><h2>Woher stammen die Beispiele und Erklärungen?</h2><p>Die Alltagsbeispiele und Erläuterungen wurden für diese Website mit KI-Unterstützung formuliert. Sie veranschaulichen die Verwendung; sie sind keine Zitate aus historischen Quellen. Die Sammlung ist ein Lernangebot und keine wissenschaftliche Ausgabe.</p><p>Bei überlieferten Sprichwörtern gibt es unterschiedliche Fassungen. Ohne geprüften Einzelbeleg geben wir keine historischen Urheber oder Entstehungsdaten an. Für wissenschaftliches Zitieren solltest du die konkrete Formulierung zusätzlich in einer belegten Sprichwörtersammlung prüfen.</p></section>
  <section><h2>Wie finde ich das passende Sprichwort?</h2><p>Suche auf der Startseite auf Deutsch, in persischer Schrift oder mit der lateinischen Umschrift. Du kannst außerdem ein Thema auswählen und zwischen „Deutsch zuerst“ und „Persisch zuerst“ wechseln. Die Einzelseiten lassen sich direkt teilen und als Lesezeichen speichern.</p><a href="/">Zur Sprichwortsammlung</a></section>
  <section><h2>Kann ich ohne Vorkenntnisse üben?</h2><p>Ja. Die kostenlose Lernprobe umfasst fünf Sprichwörter mit Umschrift und Aufgaben in beiden Sprachen. Die Erklärungen helfen dir, den passenden Zusammenhang zu erkennen.</p><a href="/lernpaket#lernprobe">Kostenlose Lernprobe öffnen</a></section>
</ContentShell>;}
