import type { Metadata } from 'next';
import { pronunciationGuideDe, pronunciationGuideFa } from '@/app/pronunciation';
import ContentShell from '@/components/content-shell';
export const metadata:Metadata={title:'Über die Sammlung: Übersetzung, Umschrift und Beispiele | Zarbol Masal',description:'So nutzt du Zarbol Masal: persischer Originaltext, vereinfachte Umschrift, deutsche Entsprechung und Alltagsbeispiele. Hinweise zu Übersetzung und Herkunft.',alternates:{canonical:'/ueber-die-sammlung'},openGraph:{title:'So funktioniert Zarbol Masal',description:'Übersetzung, Umschrift und Beispiele verständlich erklärt.',url:'/ueber-die-sammlung'}};
export default function About(){return <ContentShell>
  <nav className="content-breadcrumbs" aria-label="Brotkrumennavigation"><a href="/">Sprichwörter</a><span> / Über die Sammlung</span></nav>
  <h1>Persische Sprichwörter auf Deutsch verstehen</h1>
  <p className="content-lead">Zarbol Masal ist eine zweisprachige Lernsammlung. Sie verbindet persische Sprichwörter mit deutschen Entsprechungen, verständlichen Erklärungen und Beispielen – auch für Menschen, die keine persische Schrift lesen können.</p>
  <p lang="fa" dir="rtl">ضرب‌المثل یک مجموعهٔ آموزشی دوزبانه است. متن فارسی، آوانویسی لاتین، معادل آلمانی، معنی و مثال‌های روزمره به یادگیری کمک می‌کنند.</p>
  <section><h2>Ist die deutsche Entsprechung eine genaue Übersetzung?</h2><p>Nicht immer. Die deutsche Entsprechung stellt eine ähnliche Aussage gegenüber. Die wörtliche Übersetzung erklärt dagegen das Bild des persischen Originals. Beides wird getrennt dargestellt, weil Bedeutung und Ton nicht in jedem Zusammenhang deckungsgleich sind.</p><p>Zum Beispiel steht „Kleinvieh macht auch Mist“ neben einem persischen Sprichwort über Tropfen, die ein Meer bilden. Die Bilder unterscheiden sich; gemeinsam ist ihnen die Idee, dass viele kleine Beiträge zusammen viel bewirken.</p><a href="/sprichwoerter/1-kleinvieh-macht-auch-mist">Dieses Beispiel mit Erklärung lesen</a></section>
  <section id="umschrift"><h2>Wie liest man die deutsche Aussprachehilfe?</h2><p>Für deutschsprachige Lernende verwenden wir eine vereinfachte, deutsch orientierte Umschrift: zum Beispiel sch statt sh und dsch statt des englisch gelesenen j. Sie orientiert sich an den Konsonantenschreibungen deutschsprachiger Persisch-Sprachführer. Sie ist weder eine vollständige Lautschrift noch eine unveränderte Übernahme eines wissenschaftlichen Systems.</p><p>{pronunciationGuideDe}</p><p lang="fa" dir="rtl">{pronunciationGuideFa}</p><dl className="pronunciation-list"><dt>ش · sch</dt><dd>Wie in Schule: شب → schab.</dd><dt>چ · tsch</dt><dd>Wie in Tschüss: چرا → tscherâ.</dd><dt>ج · dsch</dt><dd>Wie in Dschungel: جوجه → dschudsche.</dd><dt>خ · ch</dt><dd>Immer wie in Bach, auch vor i oder e: خدا → chodâ.</dd><dt>ی · j</dt><dd>Als Mitlaut wie in ja: یک → jek.</dd><dt>و · w</dt><dd>Als Mitlaut wie in Wasser. Als Selbstlaut kann و dagegen beispielsweise u oder o bezeichnen.</dd><dt>ژ · ž</dt><dd>Stimmhaft wie das sch in Journal; nicht derselbe Laut wie sch in Schule.</dd></dl><p>Aussprache und Schreibweisen können regional variieren. Die Lesehilfe zielt auf iranisches Standardpersisch; sie ersetzt keine Hörbeispiele. Insbesondere Betonung und feine Lautunterschiede werden nicht vollständig dargestellt.</p><h3>Quellen zur Schreibweise</h3><p>Walther Hinz verwendet in „Persisch – Praktischer Sprachführer“, Abschnitt Lautlehre, deutsch orientierte Schreibungen wie sch, tsch, dsch und ch. Wissenschaftliche Umschriften verwenden dagegen unter anderem Zeichen wie š und č; eine Übersicht bietet die Universität Zürich. Unsere Lesehilfe behält â für das lange a sowie ž für den stimmhaften Laut bei.</p><ul><li><a href="https://api.pageplace.de/preview/DT0400.9783111558882_A37130232/preview-9783111558882_A37130232.pdf">Walther Hinz: Persisch – Praktischer Sprachführer, Lautlehre, S. 1–3 (PDF)</a></li><li><a href="https://www.aoi.uzh.ch/de/institut/it/spezifika-isl/transcription/unicode/unicodechart.html">Universität Zürich: Zeichen der wissenschaftlichen Umschrift</a></li></ul></section>
  <section><h2>Woher stammen die Beispiele und Erklärungen?</h2><p>Die Alltagsbeispiele und Erläuterungen wurden für diese Website mit KI-Unterstützung formuliert. Sie veranschaulichen die Verwendung; sie sind keine Zitate aus historischen Quellen. Die Sammlung ist ein Lernangebot und keine wissenschaftliche Ausgabe.</p><p>Bei überlieferten Sprichwörtern gibt es unterschiedliche Fassungen. Ohne geprüften Einzelbeleg geben wir keine historischen Urheber oder Entstehungsdaten an. Für wissenschaftliches Zitieren solltest du die konkrete Formulierung zusätzlich in einer belegten Sprichwörtersammlung prüfen.</p></section>
  <section><h2>Wie finde ich das passende Sprichwort?</h2><p>Suche auf der Startseite auf Deutsch, in persischer Schrift oder mit der lateinischen Umschrift. Du kannst außerdem ein Thema auswählen und zwischen „Deutsch zuerst“ und „Persisch zuerst“ wechseln. Die Einzelseiten lassen sich direkt teilen und als Lesezeichen speichern.</p><a href="/">Zur Sprichwortsammlung</a></section>
  <section><h2>Kann ich ohne Vorkenntnisse üben?</h2><p>Ja. Die kostenlose Lernprobe umfasst fünf Sprichwörter mit Umschrift und Aufgaben in beiden Sprachen. Die Erklärungen helfen dir, den passenden Zusammenhang zu erkennen.</p><a href="/lernpaket#lernprobe">Kostenlose Lernprobe öffnen</a></section>
</ContentShell>;}
